// Code generated by MockGen. DO NOT EDIT.
// Source: interceptor.go
//
// Generated by this command:
//
//	mockgen -source=interceptor.go -destination=internal/mocks/interceptor_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	yama "l7e.io/yama/v2"
)

// MockStartInterceptor is a mock of StartInterceptor interface.
type MockStartInterceptor struct {
	ctrl     *gomock.Controller
	recorder *MockStartInterceptorMockRecorder
	isgomock struct{}
}

// MockStartInterceptorMockRecorder is the mock recorder for MockStartInterceptor.
type MockStartInterceptorMockRecorder struct {
	mock *MockStartInterceptor
}

// NewMockStartInterceptor creates a new mock instance.
func NewMockStartInterceptor(ctrl *gomock.Controller) *MockStartInterceptor {
	mock := &MockStartInterceptor{ctrl: ctrl}
	mock.recorder = &MockStartInterceptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStartInterceptor) EXPECT() *MockStartInterceptorMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockStartInterceptor) Start(ctx context.Context, next yama.Starter) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", ctx, next)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockStartInterceptorMockRecorder) Start(ctx, next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockStartInterceptor)(nil).Start), ctx, next)
}

// MockQuiesceInterceptor is a mock of QuiesceInterceptor interface.
type MockQuiesceInterceptor struct {
	ctrl     *gomock.Controller
	recorder *MockQuiesceInterceptorMockRecorder
	isgomock struct{}
}

// MockQuiesceInterceptorMockRecorder is the mock recorder for MockQuiesceInterceptor.
type MockQuiesceInterceptorMockRecorder struct {
	mock *MockQuiesceInterceptor
}

// NewMockQuiesceInterceptor creates a new mock instance.
func NewMockQuiesceInterceptor(ctrl *gomock.Controller) *MockQuiesceInterceptor {
	mock := &MockQuiesceInterceptor{ctrl: ctrl}
	mock.recorder = &MockQuiesceInterceptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuiesceInterceptor) EXPECT() *MockQuiesceInterceptorMockRecorder {
	return m.recorder
}

// Quiesce mocks base method.
func (m *MockQuiesceInterceptor) Quiesce(ctx context.Context, next yama.Quiescer) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Quiesce", ctx, next)
}

// Quiesce indicates an expected call of Quiesce.
func (mr *MockQuiesceInterceptorMockRecorder) Quiesce(ctx, next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quiesce", reflect.TypeOf((*MockQuiesceInterceptor)(nil).Quiesce), ctx, next)
}

// MockStopInterceptor is a mock of StopInterceptor interface.
type MockStopInterceptor struct {
	ctrl     *gomock.Controller
	recorder *MockStopInterceptorMockRecorder
	isgomock struct{}
}

// MockStopInterceptorMockRecorder is the mock recorder for MockStopInterceptor.
type MockStopInterceptorMockRecorder struct {
	mock *MockStopInterceptor
}

// NewMockStopInterceptor creates a new mock instance.
func NewMockStopInterceptor(ctrl *gomock.Controller) *MockStopInterceptor {
	mock := &MockStopInterceptor{ctrl: ctrl}
	mock.recorder = &MockStopInterceptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStopInterceptor) EXPECT() *MockStopInterceptorMockRecorder {
	return m.recorder
}

// Stop mocks base method.
func (m *MockStopInterceptor) Stop(ctx context.Context, next yama.Stopper) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", ctx, next)
}

// Stop indicates an expected call of Stop.
func (mr *MockStopInterceptorMockRecorder) Stop(ctx, next any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockStopInterceptor)(nil).Stop), ctx, next)
}
