// Code generated by MockGen. DO NOT EDIT.
// Source: lifecycle.go
//
// Generated by this command:
//
//	mockgen -source=lifecycle.go -destination=internal/mocks/lifecycle_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStarter is a mock of Starter interface.
type MockStarter struct {
	ctrl     *gomock.Controller
	recorder *MockStarterMockRecorder
	isgomock struct{}
}

// MockStarterMockRecorder is the mock recorder for MockStarter.
type MockStarterMockRecorder struct {
	mock *MockStarter
}

// NewMockStarter creates a new mock instance.
func NewMockStarter(ctrl *gomock.Controller) *MockStarter {
	mock := &MockStarter{ctrl: ctrl}
	mock.recorder = &MockStarterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStarter) EXPECT() *MockStarterMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockStarter) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockStarterMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockStarter)(nil).Start), arg0)
}

// MockQuiescer is a mock of Quiescer interface.
type MockQuiescer struct {
	ctrl     *gomock.Controller
	recorder *MockQuiescerMockRecorder
	isgomock struct{}
}

// MockQuiescerMockRecorder is the mock recorder for MockQuiescer.
type MockQuiescerMockRecorder struct {
	mock *MockQuiescer
}

// NewMockQuiescer creates a new mock instance.
func NewMockQuiescer(ctrl *gomock.Controller) *MockQuiescer {
	mock := &MockQuiescer{ctrl: ctrl}
	mock.recorder = &MockQuiescerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQuiescer) EXPECT() *MockQuiescerMockRecorder {
	return m.recorder
}

// Quiesce mocks base method.
func (m *MockQuiescer) Quiesce(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Quiesce", arg0)
}

// Quiesce indicates an expected call of Quiesce.
func (mr *MockQuiescerMockRecorder) Quiesce(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quiesce", reflect.TypeOf((*MockQuiescer)(nil).Quiesce), arg0)
}

// MockStopper is a mock of Stopper interface.
type MockStopper struct {
	ctrl     *gomock.Controller
	recorder *MockStopperMockRecorder
	isgomock struct{}
}

// MockStopperMockRecorder is the mock recorder for MockStopper.
type MockStopperMockRecorder struct {
	mock *MockStopper
}

// NewMockStopper creates a new mock instance.
func NewMockStopper(ctrl *gomock.Controller) *MockStopper {
	mock := &MockStopper{ctrl: ctrl}
	mock.recorder = &MockStopperMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStopper) EXPECT() *MockStopperMockRecorder {
	return m.recorder
}

// Stop mocks base method.
func (m *MockStopper) Stop(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", arg0)
}

// Stop indicates an expected call of Stop.
func (mr *MockStopperMockRecorder) Stop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockStopper)(nil).Stop), arg0)
}

// MockLifecycle is a mock of Lifecycle interface.
type MockLifecycle struct {
	ctrl     *gomock.Controller
	recorder *MockLifecycleMockRecorder
	isgomock struct{}
}

// MockLifecycleMockRecorder is the mock recorder for MockLifecycle.
type MockLifecycleMockRecorder struct {
	mock *MockLifecycle
}

// NewMockLifecycle creates a new mock instance.
func NewMockLifecycle(ctrl *gomock.Controller) *MockLifecycle {
	mock := &MockLifecycle{ctrl: ctrl}
	mock.recorder = &MockLifecycleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLifecycle) EXPECT() *MockLifecycleMockRecorder {
	return m.recorder
}

// Start mocks base method.
func (m *MockLifecycle) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockLifecycleMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockLifecycle)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockLifecycle) Stop(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", arg0)
}

// Stop indicates an expected call of Stop.
func (mr *MockLifecycleMockRecorder) Stop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockLifecycle)(nil).Stop), arg0)
}
