// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package sandbox

import (
	"io"
	"os"
)

// Injectors from wire.go:

// InitializeApp builds the whole graph, logging to os.Stdout. It returns the
// aggregated cleanup and error because Base2's provider contributes both.
func InitializeApp() (*App, func(), error) {
	writer := _wireFileValue
	config := _wireConfigValue
	consoleLogger := NewConsoleLogger(writer, config)
	base1 := NewBase1(consoleLogger)
	base2, cleanup, err := NewBase2(consoleLogger)
	if err != nil {
		return nil, nil, err
	}
	mid1 := NewMid1(consoleLogger, base1, base2)
	root1 := NewRoot1(consoleLogger, mid1)
	root2 := NewRoot2(consoleLogger, mid1)
	environment := config.Env
	base3, cleanup2 := NewBase3(consoleLogger, environment)
	mid2 := NewMid2(consoleLogger, base2, base3)
	root3 := NewRoot3(consoleLogger, mid2)
	app := &App{
		root1: root1,
		root2: root2,
		root3: root3,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

var (
	_wireFileValue   = os.Stdout
	_wireConfigValue = Config{Env: Prod, LogPrefix: "[sandbox] "}
)

// InitializeAppWithWriter builds the same graph but takes the log destination as
// an argument, so the injector parameter feeds the graph in place of the
// os.Stdout interface value.
func InitializeAppWithWriter(w io.Writer) (*App, func(), error) {
	config := _wireConfigValue
	consoleLogger := NewConsoleLogger(w, config)
	base1 := NewBase1(consoleLogger)
	base2, cleanup, err := NewBase2(consoleLogger)
	if err != nil {
		return nil, nil, err
	}
	mid1 := NewMid1(consoleLogger, base1, base2)
	root1 := NewRoot1(consoleLogger, mid1)
	root2 := NewRoot2(consoleLogger, mid1)
	environment := config.Env
	base3, cleanup2 := NewBase3(consoleLogger, environment)
	mid2 := NewMid2(consoleLogger, base2, base3)
	root3 := NewRoot3(consoleLogger, mid2)
	app := &App{
		root1: root1,
		root2: root2,
		root3: root3,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
