// Code generated by Yama. DO NOT EDIT.

//go:generate go tool yama
//go:build !yamainject

package versioned

import (
	yama "l7e.io/yama/v2"
	thing "l7e.io/yama/v2/internal/generator/testdata/emit/versioned/v2"
	"l7e.io/yama/v2/rt"
)

// NewLifecycle takes a parameter whose type comes from a package imported
// without an alias, under a path ending in a version suffix.
func NewLifecycle(c *thing.Client, opts ...yama.Option) (*A, yama.Lifecycle, error) {
	a := NewA(c)

	return a,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(a).
			Build(),
		nil
}
