// Copyright (c) 2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package graph_test

import (
	"strings"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"l7e.io/yama/v2/internal/generator/graph"
)

// wireGen is Google Wire's output for one injector. It holds every form that
// Google Wire emits: a value binding, a plain provider, a provider that also
// returns a cleanup, a provider that returns a cleanup and an error, a field of
// a component, and a struct literal.
const wireGen = `// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package sandbox

func InitializeApp() (*App, func(), error) {
	config := _wireConfigValue
	logger := NewLogger(config)
	base1 := NewBase1(logger)
	base2, cleanup, err := NewBase2(logger)
	if err != nil {
		return nil, nil, err
	}
	environment := config.Env
	base3, cleanup2 := NewBase3(logger, environment)
	mid := NewMid(logger, base1, base2, base3)
	app := &App{
		mid:    mid,
		logger: logger,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

var _wireConfigValue = Config{Env: Prod}
`

// componentsOf returns the one injector that Parse found. It fails the spec
// when Parse found no injector.
func componentsOf(src, name string) []graph.Component {
	injectors, err := graph.Parse([]byte(src), []string{name})
	Expect(err).NotTo(HaveOccurred())
	Expect(injectors).To(HaveLen(1))

	return injectors[0].Components
}

// named returns the one component of that name.
func named(components []graph.Component, name string) graph.Component {
	for _, c := range components {
		if c.Name == name {
			return c
		}
	}

	Fail("no component named " + name)

	return graph.Component{}
}

var _ = Describe("Parse", func() {
	Context("when the file declares the injector", func() {
		It("names it", func() {
			injectors, err := graph.Parse([]byte(wireGen), []string{"InitializeApp"})

			Expect(err).NotTo(HaveOccurred())
			Expect(injectors[0].Name).To(Equal("InitializeApp"))
		})

		It("reads the components in the order Google Wire built them", func() {
			components := componentsOf(wireGen, "InitializeApp")

			var names []string
			for _, c := range components {
				names = append(names, c.Name)
			}

			Expect(names).To(Equal([]string{
				"config", "logger", "base1", "base2", "environment", "base3", "mid", "app",
			}))
		})

		It("leaves the capabilities empty, because the output does not state them", func() {
			for _, c := range componentsOf(wireGen, "InitializeApp") {
				Expect(c.Capabilities).To(Equal(graph.None))
			}
		})
	})

	// Google Wire writes a wire.Value provider as a read of a package-level
	// variable that its own output declares. A run takes that output out of the
	// package, so the lifecycle file states the value itself.
	Context("a value that Google Wire bound rather than built", func() {
		It("reads no dependency out of it", func() {
			Expect(named(componentsOf(wireGen, "InitializeApp"), "config").Deps).To(BeEmpty())
		})

		It("states the value in place of the variable that Google Wire wrote", func() {
			injectors, err := graph.Parse([]byte(wireGen), []string{"InitializeApp"})
			Expect(err).NotTo(HaveOccurred())

			joined := strings.Join(injectors[0].Statements, "\n")

			Expect(joined).To(ContainSubstring("config := Config{Env: Prod}"))
			Expect(joined).NotTo(ContainSubstring("_wireConfigValue"))
		})

		It("reports a read that the output declares no value for", func() {
			src := `package p

func Init() *App {
	config := _wireConfigValue
	app := NewApp(config)
	return app
}
`
			_, err := graph.Parse([]byte(src), []string{"Init"})

			Expect(err).To(MatchError(ContainSubstring("_wireConfigValue")))
		})

		It("leaves a read of a component that the injector built as it stands", func() {
			src := `package p

func Init() *App {
	a := NewA()
	b := a
	return b
}
`
			injectors, err := graph.Parse([]byte(src), []string{"Init"})

			Expect(err).NotTo(HaveOccurred())
			Expect(strings.Join(injectors[0].Statements, "\n")).To(ContainSubstring("b := a"))
		})
	})

	Context("a provider call", func() {
		It("reads every component it consumes, in order", func() {
			mid := named(componentsOf(wireGen, "InitializeApp"), "mid")

			Expect(mid.Deps).To(Equal([]string{"logger", "base1", "base2", "base3"}))
		})

		It("reads no dependency out of the provider's own name", func() {
			Expect(named(componentsOf(wireGen, "InitializeApp"), "base1").Deps).To(Equal([]string{"logger"}))
		})
	})

	Context("a provider that also returned a cleanup", func() {
		It("names the cleanup after its component when the provider returned an error too", func() {
			Expect(named(componentsOf(wireGen, "InitializeApp"), "base2").Cleanup).To(Equal("base2Cleanup"))
		})

		It("names the cleanup after its component when the provider returned no error", func() {
			Expect(named(componentsOf(wireGen, "InitializeApp"), "base3").Cleanup).To(Equal("base3Cleanup"))
		})

		It("names no cleanup for a provider that returned none", func() {
			Expect(named(componentsOf(wireGen, "InitializeApp"), "logger").Cleanup).To(BeEmpty())
		})

		It("binds the cleanup under its new name in the printed statements", func() {
			injectors, err := graph.Parse([]byte(wireGen), []string{"InitializeApp"})
			Expect(err).NotTo(HaveOccurred())

			joined := strings.Join(injectors[0].Statements, "\n")

			Expect(joined).To(ContainSubstring("base2, base2Cleanup, err := NewBase2(logger)"))
			Expect(joined).To(ContainSubstring("base3, base3Cleanup := NewBase3(logger, environment)"))
		})
	})

	Context("a field of a component", func() {
		It("reads the component and not the field name", func() {
			Expect(named(componentsOf(wireGen, "InitializeApp"), "environment").Deps).To(Equal([]string{"config"}))
		})
	})

	Context("a struct literal", func() {
		It("reads the values and not the field keys", func() {
			Expect(named(componentsOf(wireGen, "InitializeApp"), "app").Deps).To(Equal([]string{"mid", "logger"}))
		})
	})

	Context("a component that one call consumes twice", func() {
		It("names it once", func() {
			src := `package p

func Init() *App {
	a := NewA()
	b := NewB(a, a)
	return b
}
`
			Expect(named(componentsOf(src, "Init"), "b").Deps).To(Equal([]string{"a"}))
		})
	})

	// Google Wire writes a declaration for each value that it builds, an error
	// check, and a return. Parse reports every other shape. A value that reaches
	// no component reaches no lifecycle level, and the lifecycle would run
	// without that value.
	Context("a statement that states no dependency", func() {
		// parsed returns what Parse produced for one injector body.
		parsed := func(body string) error {
			_, err := graph.Parse([]byte("package p\n\nfunc Init() *App {\n"+body+"}\n"), []string{"Init"})

			return err
		}

		It("reports an assignment that declares nothing", func() {
			Expect(parsed("\tother = NewA()\n\tb := NewB()\n\treturn b\n")).To(MatchError(
				ContainSubstring("no traceable dependency edge: a value reaches the graph through a variable assignment")))
		})

		It("tells a field write apart from a plain assignment", func() {
			Expect(parsed("\tx.field = a\n\tb := NewB()\n\treturn b\n")).To(
				MatchError(ContainSubstring("through a field assignment")))
		})

		It("names the value that an assignment places", func() {
			Expect(parsed("\tother = a\n\tb := NewB()\n\treturn b\n")).To(
				MatchError(ContainSubstring("a reaches the graph")))
		})

		It("names the shape of a statement that is no declaration", func() {
			Expect(parsed("\tgo NewA()\n\tb := NewB()\n\treturn b\n")).To(
				MatchError(ContainSubstring("unsupported statement: go statement")))
		})

		It("names the shape of each unsupported statement", func() {
			Expect(parsed("\tdefer NewA()\n\tb := NewB()\n\treturn b\n")).To(
				MatchError(ContainSubstring("defer statement")))

			Expect(parsed("\tfor {\n\t}\n\tb := NewB()\n\treturn b\n")).To(
				MatchError(ContainSubstring("loop")))
		})

		It("names the shape of a form that no provider writes", func() {
			Expect(parsed("\ta := 1 + 2\n\treturn a\n")).To(
				MatchError(ContainSubstring("unrecognized provider form: a is bound to a binary expression")))
		})

		It("names the shape of each form that no provider writes", func() {
			Expect(parsed("\ta := func() {}\n\treturn a\n")).To(
				MatchError(ContainSubstring("function literal")))

			Expect(parsed("\ta := 1\n\treturn a\n")).To(
				MatchError(ContainSubstring("literal value")))
		})

		It("names the position that the statement holds", func() {
			err := parsed("\ta := NewA()\n\tgo NewB()\n\treturn a\n")

			Expect(err).To(MatchError(ContainSubstring("wire_gen.go:5:2")))
		})

		It("names the injector that holds the statement", func() {
			Expect(parsed("\tgo NewA()\n\treturn nil\n")).To(
				MatchError(ContainSubstring("injector Init:")))
		})

		It("reports a body that does not end in a return", func() {
			Expect(parsed("\ta := NewA()\n")).To(
				MatchError(ContainSubstring("does not end in a return statement")))
		})

		It("takes the error check that Google Wire writes", func() {
			body := "\ta, err := NewA()\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\treturn a\n"

			Expect(parsed(body)).NotTo(HaveOccurred())
		})

		It("takes a declaration whose first name binds nothing", func() {
			body := "\t_, b := NewA()\n\treturn b\n"

			Expect(parsed(body)).NotTo(HaveOccurred())
		})

		It("takes every form that a Google Wire provider writes", func() {
			body := "\ta := NewA()\n\tb := _wireValue\n\tc := B{}\n\td := &B{}\n\te := a.Field\n\treturn e\n"
			src := "package p\n\nfunc Init() *App {\n" + body + "}\n\nvar _wireValue = B{}\n"

			_, err := graph.Parse([]byte(src), []string{"Init"})

			Expect(err).NotTo(HaveOccurred())
		})
	})

	Context("when the file does not declare a wanted injector", func() {
		It("leaves that name out", func() {
			injectors, err := graph.Parse([]byte(wireGen), []string{"Absent"})

			Expect(err).NotTo(HaveOccurred())
			Expect(injectors).To(BeEmpty())
		})
	})

	Context("when the file does not parse", func() {
		It("reports that it could not read Google Wire's output", func() {
			_, err := graph.Parse([]byte("package p\n\nfunc Broken( {\n"), []string{"Broken"})

			Expect(err).To(MatchError(ContainSubstring("google wire")))
		})
	})

	Context("with Levels", func() {
		It("assigns the levels that the parsed graph implies", func() {
			components := componentsOf(wireGen, "InitializeApp")

			// Only base2 and base3 occupy a level here, because a parsed
			// component declares no capability and those two carry a cleanup.
			levels := graph.Levels(components)

			Expect(names(levels)).To(Equal([][]string{{"base2", "base3"}}))
		})
	})
})
