// Code generated by Yama. DO NOT EDIT.

//go:generate go tool yama
//go:build !yamainject

package closer

import (
	"l7e.io/yama"
	"l7e.io/yama/rt"
)

func NewLifecycle(opts ...yama.Option) (*Root, yama.Lifecycle, error) {
	conn := NewConn()
	pool := &Pool{
		Conn: conn,
	}
	out := NewOut()
	log := NewLog()
	root := NewRoot(pool, out, log)

	return root,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(rt.AsStopper(conn)).
			NextLevel().
			WithComponents(rt.AsStopper(pool)).
			NextLevel().
			WithComponents(root).
			Build(),
		nil
}
