os:
  - linux
  - osx
  - windows
sudo: false
language: go
go_import_path: l7e.io/yama
# Force-enable Go modules. Also force go to use the code in vendor/
env: GO111MODULE=on
go:
  - 1.11.x
  - 1.12.x
  - 1.13.x
  - 1.14.x
  - 1.15.x
before_install:
  - |
    if [ "$TRAVIS_OS_NAME" = 'linux' ] && [ "$TRAVIS_GO_VERSION" =~ ^1\.15 ]; then
      go get -u github.com/golangci/golangci-lint/cmd/golangci-lint@1.30.0
    fi
  - go install github.com/mattn/goveralls
script:
  - |
    if [ "$TRAVIS_OS_NAME" = 'linux' ] && [ "$TRAVIS_GO_VERSION" =~ ^1\.15 ]; then
      $GOPATH/bin/golangci-lint run -v
    fi
  - $GOPATH/bin/goveralls -service=travis-ci -race -v
after_success:
  - bash <(curl -s https://codecov.io/bash)
