// Code generated by Yama. DO NOT EDIT.

//go:build !yamainject

package capabilities

import (
	yama "l7e.io/yama/v2"
	"l7e.io/yama/v2/rt"
)

// NewLifecycle orchestrates one component per capability set.
func NewLifecycle(opts ...yama.Option) (*Everything, yama.Lifecycle, error) {
	inert := NewInert()
	startOnly := NewStartOnly(inert)
	quiesceOnly := NewQuiesceOnly(inert)
	stopOnly := NewStopOnly(inert)
	everything := NewEverything(startOnly, quiesceOnly, stopOnly)

	return everything,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(startOnly).
			WithComponents(quiesceOnly).
			WithComponents(stopOnly).
			NextLevel().
			WithComponents(everything).
			Build(),
		nil
}
