// Code generated by Yama. DO NOT EDIT.

//go:generate go tool yama
//go:build !yamainject

package variadicgraphparam

import (
	yama "l7e.io/yama/v2"
	"l7e.io/yama/v2/rt"
)

// NewLifecycle declares a final parameter that is variadic but not
// yama.Option: a graph parameter, not an options parameter.
func NewLifecycle(names ...string) (*App, yama.Lifecycle, error) {
	app := NewApp()

	return app,
		rt.NewLifecycleBuilder().
			Build(),
		nil
}
