// Copyright (c) 2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package wire_test

import (
	"context"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"l7e.io/yama/internal/generator/pkg"
	"l7e.io/yama/internal/generator/wire"
)

// appStub is the one stub that every package here declares. A spec that needs
// another shape takes this one and states the field that it changes.
func appStub() pkg.Stub {
	return pkg.Stub{
		Name: "NewAppLifecycle",
		Params: []pkg.Field{
			{Name: "ctx", Type: "context.Context"},
			{Name: "opts", Type: "...yama.Option"},
		},
		Results: []pkg.Field{
			{Type: "*applib.Lifecycle"},
			{Type: "error"},
		},
		Providers: []string{"applib.NewDB", "applib.ProviderSet"},
		HasOpts:   true,
	}
}

// appImports is the import block that every package here carries.
func appImports() []pkg.Import {
	return []pkg.Import{
		{Path: "context"},
		{Path: "github.com/google/wire"},
		{Name: "applib", Path: "example.com/app/lib"},
	}
}

// infoOf is one target package that declares the stubs and the imports that it
// states.
func infoOf(stubs []pkg.Stub, imports []pkg.Import) *pkg.Info {
	target := pkg.NewInfo("")
	target.TakeStubFile("app", stubs, imports)

	return target
}

// info is one target package that declares one stub taking options.
func info() *pkg.Info {
	return infoOf([]pkg.Stub{appStub()}, appImports())
}

// stubbed is one target package. Its one stub took the change that with made.
func stubbed(with func(*pkg.Stub)) *pkg.Info {
	stub := appStub()
	with(&stub)

	return infoOf([]pkg.Stub{stub}, appImports())
}

// positioned is the same package. Its stub states the file and the position
// where a person wrote the stub.
func positioned() *pkg.Info {
	return stubbed(func(s *pkg.Stub) {
		s.File = "lifecycle.go"
		s.Line = 27
		s.Column = 1
	})
}

var _ = Describe("wire", func() {
	Describe("DerivedName", func() {
		It("starts the stub's name with a prefix of its own", func() {
			Expect(wire.DerivedName("NewAppLifecycle")).To(Equal("yama_NewAppLifecycle"))
		})
	})

	Describe("OutputName", func() {
		It("returns the plain name when the run set no prefix", func() {
			Expect(wire.OutputName("")).To(Equal("wire_gen.go"))
		})

		It("starts the name with the run's prefix", func() {
			Expect(wire.OutputName("foo_")).To(Equal("foo_wire_gen.go"))
		})
	})

	Describe("Derive", func() {
		It("assembles a file that go/format accepts", func() {
			Expect(string(wire.Derive(info()))).To(Equal(`// Code generated by Yama. DO NOT EDIT.

//go:build wireinject

package app

import (
	context "context"
	applib "example.com/app/lib"
	wire "github.com/google/wire"
)

func yama_NewAppLifecycle(ctx context.Context) (*applib.Lifecycle, func(), error) {
	panic(wire.Build(applib.NewDB, applib.ProviderSet))
}
`))
		})

		It("lets go/format sort the import block by path", func() {
			derived := string(wire.Derive(info()))

			Expect(derived).To(ContainSubstring("\tcontext \"context\"\n\tapplib \"example.com/app/lib\"\n\twire \"github.com/google/wire\"\n"))
		})

		It("guards the file with the tag that only Google Wire sets", func() {
			Expect(string(wire.Derive(info()))).To(ContainSubstring("//go:build wireinject"))
		})

		Context("the derived injector", func() {
			It("drops the stub's trailing option parameter", func() {
				Expect(string(wire.Derive(info()))).To(ContainSubstring("func yama_NewAppLifecycle(ctx context.Context)"))
			})

			It("keeps the stub's provider list as it was written", func() {
				Expect(string(wire.Derive(info()))).To(ContainSubstring("wire.Build(applib.NewDB, applib.ProviderSet)"))
			})

			It("returns the stub's first result, a cleanup, and an error", func() {
				derived := string(wire.Derive(info()))

				Expect(derived).To(ContainSubstring("(*applib.Lifecycle, func(), error)"))
			})

			It("drops the stub's own lifecycle result, which Google Wire rejects", func() {
				p := stubbed(func(s *pkg.Stub) {
					s.Results = []pkg.Field{
						{Type: "*applib.App"},
						{Type: "yama.Lifecycle"},
						{Type: "error"},
					}
				})

				derived := string(wire.Derive(p))

				Expect(derived).To(ContainSubstring("(*applib.App, func(), error)"))
				Expect(derived).NotTo(ContainSubstring("yama.Lifecycle"))
			})
		})

		Context("a stub that takes no options", func() {
			It("gives the injector the same parameters as the stub", func() {
				p := stubbed(func(s *pkg.Stub) {
					s.HasOpts = false
					s.Params = []pkg.Field{{Name: "ctx", Type: "context.Context"}}
				})

				Expect(string(wire.Derive(p))).To(ContainSubstring("func yama_NewAppLifecycle(ctx context.Context)"))
			})
		})

		Context("a package that declares several stubs", func() {
			It("writes an injector for each", func() {
				other := pkg.Stub{
					Name:      "NewOther",
					Results:   []pkg.Field{{Type: "error"}},
					Providers: []string{"applib.Other"},
				}

				p := infoOf([]pkg.Stub{appStub(), other}, appImports())

				derived := string(wire.Derive(p))

				Expect(derived).To(ContainSubstring("func yama_NewAppLifecycle("))
				Expect(derived).To(ContainSubstring("func yama_NewOther("))
			})

			It("writes no placeholder", func() {
				Expect(string(wire.Derive(info()))).NotTo(ContainSubstring("func NewAppLifecycle("))
			})
		})

		Context("an import that the path does not name", func() {
			// gopkg.in/yaml.v3 declares the package yaml. A file that refers to
			// yaml.Node must import the path under that name. No rule over
			// the path alone produces that name.
			It("writes the name that the package declares", func() {
				stub := appStub()
				stub.Results = []pkg.Field{{Type: "*yaml.Node"}, {Type: "error"}}

				imports := append(appImports(), pkg.Import{Path: "gopkg.in/yaml.v3"})
				p := infoOf([]pkg.Stub{stub}, imports)

				Expect(p.TakeImportNames(map[string]string{"gopkg.in/yaml.v3": "yaml"})).To(Succeed())

				Expect(string(wire.Derive(p))).To(ContainSubstring(`yaml "gopkg.in/yaml.v3"`))
			})

			It("drops the import when no name it holds matches the code", func() {
				imports := append(appImports(), pkg.Import{Path: "gopkg.in/yaml.v3"})
				p := infoOf([]pkg.Stub{appStub()}, imports)

				Expect(string(wire.Derive(p))).NotTo(ContainSubstring("gopkg.in/yaml.v3"))
			})
		})

		// Google Wire loads the derived file through go/packages. go/packages
		// applies a line directive. Google Wire then reports the file that a
		// person wrote, at the position where that person wrote the stub.
		It("puts each declaration at the position of the stub that it comes from", func() {
			Expect(string(wire.Derive(positioned()))).To(ContainSubstring("\n//line lifecycle.go:27:1\n"))
		})

		// A stub can import Google Wire under an alias. buildCall takes the
		// call whatever that alias is. The derived injector states the same
		// alias, and the import block binds it.
		Context("a stub that names Google Wire by an alias", func() {
			It("calls Build through that alias", func() {
				stub := appStub()
				stub.Wire = "gwire"

				imports := []pkg.Import{
					{Path: "context"},
					{Name: "gwire", Path: "github.com/google/wire"},
					{Name: "applib", Path: "example.com/app/lib"},
				}

				derived := string(wire.Derive(infoOf([]pkg.Stub{stub}, imports)))

				Expect(derived).To(ContainSubstring("panic(gwire.Build("))
				Expect(derived).To(ContainSubstring(`gwire "github.com/google/wire"`))
				Expect(derived).NotTo(ContainSubstring("panic(wire.Build("))
			})
		})

		Context("a package that imports nothing", func() {
			It("writes no import block", func() {
				stub := appStub()
				stub.Params = nil
				stub.Results = []pkg.Field{{Type: "error"}}
				stub.HasOpts = false
				stub.Providers = []string{"One"}

				p := infoOf([]pkg.Stub{stub}, nil)

				Expect(string(wire.Derive(p))).NotTo(ContainSubstring("import"))
			})
		})
	})

	Describe("DerivePlaceholder", func() {
		It("assembles a file that go/format accepts", func() {
			Expect(string(wire.DerivePlaceholder(info()))).To(Equal(`// Code generated by Yama. DO NOT EDIT.

//go:build !yamainject

package app

import (
	context "context"
	applib "example.com/app/lib"
)

func NewAppLifecycle(ctx context.Context, opts ...yama.Option) (*applib.Lifecycle, error) {
	panic("yama: NewAppLifecycle is not generated")
}
`))
		})

		It("leaves out Google Wire, which a placeholder never calls", func() {
			Expect(string(wire.DerivePlaceholder(info()))).NotTo(ContainSubstring("github.com/google/wire"))
		})

		It("carries the build constraint that the lifecycle file carries", func() {
			Expect(string(wire.DerivePlaceholder(info()))).To(ContainSubstring("//go:build !yamainject"))
		})

		It("declares the stub's own name and full parameter list", func() {
			placeholder := string(wire.DerivePlaceholder(info()))

			Expect(placeholder).To(ContainSubstring("func NewAppLifecycle(ctx context.Context, opts ...yama.Option)"))
		})

		It("panics with a message that names the stub", func() {
			Expect(string(wire.DerivePlaceholder(info()))).To(ContainSubstring(`panic("yama: NewAppLifecycle is not generated")`))
		})

		It("writes no derived injector", func() {
			Expect(string(wire.DerivePlaceholder(info()))).NotTo(ContainSubstring("yama_NewAppLifecycle"))
		})

		It("puts each declaration at the position of the stub it comes from", func() {
			Expect(string(wire.DerivePlaceholder(positioned()))).To(ContainSubstring("\n//line lifecycle.go:27:1\n"))
		})

		Context("a package that declares several stubs", func() {
			It("declares each stub's own name", func() {
				other := pkg.Stub{
					Name:      "NewOther",
					Results:   []pkg.Field{{Type: "error"}},
					Providers: []string{"applib.Other"},
				}

				p := infoOf([]pkg.Stub{appStub(), other}, appImports())

				placeholder := string(wire.DerivePlaceholder(p))

				Expect(placeholder).To(ContainSubstring("func NewAppLifecycle("))
				Expect(placeholder).To(ContainSubstring("func NewOther("))
			})
		})
	})

	Describe("Args", func() {
		It("returns no flag when a run set none", func() {
			Expect(wire.Args{}.Flags()).To(BeEmpty())
		})

		It("returns one flag for each value a run set", func() {
			args := wire.Args{HeaderFile: "header.txt", Tags: "special", Prefix: "foo_"}

			Expect(args.Flags()).To(Equal([]string{
				"-header_file=header.txt",
				"-tags=special",
				"-output_file_prefix=foo_",
			}))
		})

		It("leaves out a value that a run did not set", func() {
			Expect(wire.Args{Tags: "special"}.Flags()).To(Equal([]string{"-tags=special"}))
		})

		// The go command separates two tags with a comma or with a space. Every
		// load that Yama makes takes them one at a time. A load that read them
		// another way would see another set of files.
		Describe("TagList", func() {
			It("returns nothing when a run set no tag", func() {
				Expect(wire.Args{}.TagList()).To(BeEmpty())
			})

			It("returns the one tag that a run set", func() {
				Expect(wire.Args{Tags: "special"}.TagList()).To(Equal([]string{"special"}))
			})

			It("splits two tags that a comma separates", func() {
				Expect(wire.Args{Tags: "a,b"}.TagList()).To(Equal([]string{"a", "b"}))
			})

			It("splits two tags that a space separates", func() {
				Expect(wire.Args{Tags: "a b"}.TagList()).To(Equal([]string{"a", "b"}))
			})

			It("splits two tags that a comma and a space separate", func() {
				Expect(wire.Args{Tags: "a, b"}.TagList()).To(Equal([]string{"a", "b"}))
			})
		})
	})

	Describe("Run", func() {
		It("starts no subprocess when a run resolved no pattern", func() {
			logged, err := wire.Run(context.Background(), GinkgoT().TempDir(), nil, wire.Args{})

			Expect(err).NotTo(HaveOccurred())
			Expect(logged).To(BeEmpty())
		})

		It("reports the directory it could not run in", func() {
			_, err := wire.Run(context.Background(), "/nonexistent", []string{"."}, wire.Args{})

			Expect(err).To(MatchError(ContainSubstring("/nonexistent")))
		})

		It("returns what Google Wire printed", func() {
			logged, err := wire.Run(context.Background(), GinkgoT().TempDir(), []string{"."}, wire.Args{})

			Expect(err).To(HaveOccurred())
			Expect(logged).NotTo(BeEmpty())
		})
	})
})
