// Code generated by Yama. DO NOT EDIT.

//go:generate go tool yama
//go:build !yamainject

package hello

import (
	"io"

	"l7e.io/yama"
	"l7e.io/yama/rt"
)

// NewLifecycle orchestrates the graph GraphSet builds, reporting to w.
func NewLifecycle(w io.Writer, opts ...yama.Option) (*Server, yama.Lifecycle, error) {
	config := NewConfig()
	store, storeCleanup := NewStore(w, config)
	server := NewServer(w, store)

	return server,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithCleanableComponent(store, storeCleanup).
			NextLevel().
			WithComponents(server).
			Build(),
		nil
}
