// Code generated by Yama. DO NOT EDIT.

//go:build !yamainject

package optsshadow

import (
	yama "l7e.io/yama/v2"
	"l7e.io/yama/v2/internal/generator/testdata/emit/optsshadow/rt"
	rt3 "l7e.io/yama/v2/rt"
)

// NewLifecycle names its options parameter rt, which is also the name the
// re-emitted body refers to a provider's package by. The body's import cannot
// move, so the parameter is what gives way.
func NewLifecycle(rt2 ...yama.Option) (*A, yama.Lifecycle, error) {
	clock := rt.NewClock()
	a := NewA(clock)

	return a,
		rt3.NewLifecycleBuilder(rt2...).
			NextLevel().
			WithComponents(a).
			Build(),
		nil
}
