// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package typeerror

// Injectors from wire.go:

func InitializeApp() (*App, error) {
	app := NewApp()
	return app, nil
}
