// Code generated by Yama. DO NOT EDIT.

//go:build !yamainject

package diamond

import (
	yama "l7e.io/yama/v2"
	"l7e.io/yama/v2/rt"
)

// NewLifecycle orchestrates a diamond graph.
func NewLifecycle(opts ...yama.Option) (*Top, yama.Lifecycle, error) {
	base := NewBase()
	left := NewLeft(base)
	right := NewRight(base)
	top := NewTop(left, right)

	return top,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(base).
			NextLevel().
			WithComponents(left).
			WithComponents(right).
			NextLevel().
			WithComponents(top).
			Build(),
		nil
}
