// Copyright (c) 2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package wire_test

import (
	"os"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"l7e.io/yama/v2/internal/generator/sketch/pkg"
	"l7e.io/yama/v2/internal/generator/sketch/wire"
)

// A run takes no custody of the two intermediate names. It never puts back a
// file that it wrote over, so it writes over no file that it did not write
// itself.
var _ = Describe("IntermediateYamaFiles", func() {
	var (
		dir   string
		files *wire.IntermediateYamaFiles
	)

	BeforeEach(func() {
		dir = GinkgoT().TempDir()

		target := pkg.NewInfo(dir)
		target.TakeStubFile("app", []pkg.Stub{appStub()}, appImports())

		files = wire.NewIntermediateYamaFiles(target)
	})

	Context("a name that the directory already holds", func() {
		var mine string

		BeforeEach(func() {
			mine = filepath.Join(dir, wire.PlaceholderFileName)
			Expect(os.WriteFile(mine, []byte("package app\n\nconst UserOwned = 1\n"), 0o600)).To(Succeed())
		})

		It("reports the name rather than writing over it", func() {
			Expect(files.Prepare()).To(MatchError(ContainSubstring("already holds that name")))
		})

		It("leaves the file the user owns byte for byte", func() {
			Expect(files.Prepare()).NotTo(Succeed())

			Expect(os.ReadFile(mine)).To(Equal([]byte("package app\n\nconst UserOwned = 1\n")))
		})

		It("takes out what it wrote, and leaves the file the user owns", func() {
			Expect(files.Prepare()).NotTo(Succeed())
			Expect(files.CleanUp()).To(Succeed())

			Expect(mine).To(BeAnExistingFile())
			Expect(filepath.Join(dir, wire.DerivedFileName)).NotTo(BeAnExistingFile())
		})
	})

	Context("a name that a run which ended early left", func() {
		BeforeEach(func() {
			stale := "// Code generated by Yama. DO NOT EDIT.\n\n//go:build !yamainject\n\npackage app\n"
			path := filepath.Join(dir, wire.PlaceholderFileName)

			Expect(os.WriteFile(path, []byte(stale), 0o600)).To(Succeed())
		})

		It("writes over it and takes both names back out", func() {
			Expect(files.Prepare()).To(Succeed())
			Expect(files.CleanUp()).To(Succeed())

			Expect(filepath.Join(dir, wire.PlaceholderFileName)).NotTo(BeAnExistingFile())
			Expect(filepath.Join(dir, wire.DerivedFileName)).NotTo(BeAnExistingFile())
		})
	})
})
