// Copyright (c) 2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package wire derives a Google Wire injector from a lifecycle stub. It also
// runs Google Wire over a set of directories.
//
// Derive takes data and returns bytes, so it needs no Go toolchain. Run is the
// one place in the tree that starts a subprocess.
package wire

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"go/format"
	"go/scanner"
	"go/token"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"unicode"

	"l7e.io/yama/v2/internal/generator/sketch/pkg"
)

const (
	// Tag guards the derived injector file. Only Google Wire's own load sets
	// it, so every later load ignores that file.
	Tag = "wireinject"

	// DerivedFileName is the file that Derive's bytes go into.
	DerivedFileName = "yama_wireinject.go"

	// PlaceholderFileName is the file that DerivePlaceholder's bytes go into.
	PlaceholderFileName = "yama_placeholder.go"

	// derivedPrefix starts the name of a derived injector, so the injector
	// never collides with the stub that it comes from.
	derivedPrefix = "yama_"

	// BaseOutputName is the file that Google Wire writes.
	BaseOutputName = "wire_gen.go"

	// PackagePath is Google Wire itself. A stub imports it for wire.Build. The
	// lifecycle file that Yama writes never uses it.
	PackagePath = pkg.WirePackagePath
)

// fileMode is the mode that wire gives the derived file that it writes.
const fileMode = 0o600

// buildFunc is the function that carries a derived injector's provider list.
const buildFunc = "Build"

// generatedMarker starts every file that this package writes. write replaces a
// file that carries this marker. write refuses a file that does not carry it.
const generatedMarker = "// Code generated by Yama. DO NOT EDIT."

// linePrefix begins a Go line directive. A directive moves every position
// after it onto the file and line that it names.
const linePrefix = "//line "

// These are the markers of Google Wire's own diagnostic. wroteMarker introduces
// the path in the line that reports an output file. injectMarker introduces the
// injector name in the line that reports one injector.
const (
	wroteMarker  = ": wrote "
	injectMarker = "inject "
)

// placeholderPanic is the body of a lifecycle placeholder. A placeholder lets
// the package type-check while its committed file is set aside.
const placeholderPanic = "yama: %s is not generated"

// DerivedName returns the injector that Yama derives from the named stub.
func DerivedName(stub string) string {
	return derivedPrefix + stub
}

// DerivedNames returns the injector that Yama derives for each of the package's
// stubs, in the order that the package declares them.
func DerivedNames(info *pkg.Info) []string {
	names := make([]string, 0, len(info.Stubs()))

	for i := range info.Stubs() {
		names = append(names, DerivedName(info.Stubs()[i].Name))
	}

	return names
}

// OutputName returns the file that Google Wire writes for the given
// output-file prefix.
func OutputName(prefix string) string {
	return prefix + BaseOutputName
}

// Derive assembles the derived injector file for one target package. The file
// holds one injector for each stub. Google Wire's own load is the one load that
// reads it.
//
// Derive panics when go/format rejects what it assembled. Every such failure is
// a bug in Derive itself.
func Derive(info *pkg.Info) []byte {
	body := assemble(info, writeInjector)

	return file(info, Tag, body, DerivedFileName)
}

// DerivePlaceholder assembles the placeholder file for one target package. The
// file holds one declaration of each stub's own name. It takes the place of the
// lifecycle file while that file is set aside.
//
// The placeholder file carries the build constraint that the lifecycle file
// carries. Google Wire's load reads it. The load that reads Google Wire's
// output also reads it. The two loads set different tags. Each load needs the
// name.
//
// DerivePlaceholder panics when go/format rejects what it assembled. Every such
// failure is a bug in DerivePlaceholder itself.
func DerivePlaceholder(info *pkg.Info) []byte {
	body := assemble(info, writePlaceholder)

	return file(info, "!"+pkg.Tag, body, PlaceholderFileName)
}

// assemble writes one declaration for each stub, with write.
func assemble(info *pkg.Info, write func(*bytes.Buffer, *pkg.Stub)) []byte {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "package %s\n", info.Name())

	for i := range info.Stubs() {
		write(&buf, &info.Stubs()[i])
	}

	return buf.Bytes()
}

// file puts the build constraint, the package clause, the import block, and the
// body together. It keeps the imports that the body refers to. Go rejects a
// file that imports a package that it never uses. Each transient file uses only
// part of what the stub file imported.
//
// file panics when go/format rejects what it put together. Every such failure
// is a bug in file itself.
func file(info *pkg.Info, constraint string, body []byte, name string) []byte {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "%s\n\n", generatedMarker)
	fmt.Fprintf(&buf, "//go:build %s\n\n", constraint)
	fmt.Fprintf(&buf, "package %s\n", info.Name())

	used := pkg.Qualifiers(body)
	writeImports(&buf, needed(info, used))

	_, declarations, _ := bytes.Cut(body, []byte("\n"))
	buf.Write(declarations)

	src, err := format.Source(buf.Bytes())
	if err != nil {
		panic(fmt.Sprintf("wire: go/format rejected %s: %v\n%s", name, err, buf.String()))
	}

	return src
}

// needed returns the imports that the body refers to. Each import that needed
// returns carries an explicit name. Because of this, a path still resolves if
// its last element is not the package name.
func needed(info *pkg.Info, used map[string]bool) []pkg.Import {
	out := make([]pkg.Import, 0, len(info.Imports()))

	for _, imp := range info.Imports() {
		name := info.NameOf(imp)

		if used[name] {
			out = append(out, pkg.Import{Name: name, Path: imp.Path})
		}
	}

	return out
}

// write puts one of this package's transient files in dir.
//
// A run takes no custody of these two names, so it never puts back a file that
// it wrote over. write replaces a file that carries generatedMarker. A run that
// ended early leaves such a file behind. write reports every other file, and
// that file keeps the bytes that it holds.
func write(dir, name string, content []byte) error {
	path := filepath.Join(dir, name)

	if err := checkOwn(path); err != nil {
		return fmt.Errorf("write %s in %s: %w", name, dir, err)
	}

	if err := os.WriteFile(path, content, fileMode); err != nil {
		return fmt.Errorf("write %s in %s: %w", name, dir, err)
	}

	return nil
}

// checkOwn reports a file at path that this package did not write. A path that
// names no file is not an error.
func checkOwn(path string) error {
	present, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return nil
	}

	if err != nil {
		return err
	}

	if !bytes.HasPrefix(present, []byte(generatedMarker)) {
		return errors.New("the directory already holds that name")
	}

	return nil
}

// remove takes one of this package's transient files out of dir.
func remove(dir, name string) error {
	err := os.Remove(filepath.Join(dir, name))
	if err == nil || os.IsNotExist(err) {
		return nil
	}

	return fmt.Errorf("remove %s in %s: %w", name, dir, err)
}

// Args are the flags that a run passes through to Google Wire. Each field
// matches a flag of `wire gen`.
type Args struct {
	HeaderFile string
	Tags       string
	Prefix     string
}

// TagList returns the build tags that the run set, one entry for each. Google
// Wire takes them as one value. Every load that Yama makes takes them one at a
// time.
//
// The go command separates two tags with a comma or with a space. TagList
// splits on both, so every load reads the tags that the go command reads.
func (a Args) TagList() []string {
	return strings.FieldsFunc(a.Tags, tagSeparator)
}

// Flags returns the flag list that these arguments produce, in a fixed order.
func (a Args) Flags() []string {
	var flags []string

	for _, each := range []struct{ name, value string }{
		{"header_file", a.HeaderFile},
		{"tags", a.Tags},
		{"output_file_prefix", a.Prefix},
	} {
		if each.value != "" {
			flags = append(flags, "-"+each.name+"="+each.value)
		}
	}

	return flags
}

// Run invokes Google Wire one time over patterns, from dir. It returns whatever
// Google Wire printed.
//
// Run reports both kinds of failure through its error. Google Wire can reject
// an input, and the tool can fail to start. Both are the same signal here. The
// run failed, and the diagnostic that Run returns states the cause.
func Run(ctx context.Context, dir string, patterns []string, args Args) (string, error) {
	if len(patterns) == 0 {
		return "", nil
	}

	argv := append([]string{"tool", "wire", "gen"}, args.Flags()...)
	argv = append(argv, patterns...)

	var stdout, stderr bytes.Buffer

	cmd := exec.CommandContext(ctx, "go", argv...)
	cmd.Dir = dir
	cmd.Stdout = &stdout
	cmd.Stderr = &stderr

	err := cmd.Run()
	logged := strings.TrimSpace(stderr.String() + stdout.String())

	if err == nil {
		return logged, nil
	}

	return logged, fmt.Errorf("google wire failed in %s: %w", dir, err)
}

// writeImports writes the import block of the derived file.
func writeImports(buf *bytes.Buffer, block []pkg.Import) {
	if len(block) == 0 {
		return
	}

	buf.WriteString("\nimport (\n")

	for _, imp := range block {
		if imp.Name != "" {
			fmt.Fprintf(buf, "\t%s %q\n", imp.Name, imp.Path)

			continue
		}

		fmt.Fprintf(buf, "\t%q\n", imp.Path)
	}

	buf.WriteString(")\n")
}

// writeInjector writes the injector that Google Wire reads. The injector takes
// the stub's parameters without its trailing option parameter. It keeps the
// stub's own provider list.
//
// The injector returns the stub's first result, a cleanup, and an error. Google
// Wire accepts no other result list. It accepts a cleanup result whether or not
// a provider contributes one.
func writeInjector(buf *bytes.Buffer, stub *pkg.Stub) {
	writeLine(buf, stub)

	params := fieldList(stub.GraphParams())
	result := stub.ResultType()
	providers := strings.Join(stub.Providers, ", ")
	qualifier := stub.WireName()

	fmt.Fprintf(buf, "\nfunc %s(%s) (%s, func(), error) {\n", DerivedName(stub.Name), params, result)
	fmt.Fprintf(buf, "\tpanic(%s.%s(%s))\n}\n", qualifier, buildFunc, providers)
}

// writePlaceholder writes a declaration of the stub's own name, so the package
// still type-checks while its committed file is set aside.
func writePlaceholder(buf *bytes.Buffer, stub *pkg.Stub) {
	writeLine(buf, stub)

	params := fieldList(stub.Params)
	results := fieldList(stub.Results)
	message := fmt.Sprintf(placeholderPanic, stub.Name)

	fmt.Fprintf(buf, "\nfunc %s(%s) (%s) {\n", stub.Name, params, results)
	fmt.Fprintf(buf, "\tpanic(%q)\n}\n", message)
}

// writeLine writes the line directive that puts the declaration after it at the
// stub's own position. Google Wire loads the file through go/packages.
// go/packages applies the directive, so Google Wire reports the file that a
// person wrote.
//
// writeLine writes nothing for a stub with no position.
func writeLine(buf *bytes.Buffer, stub *pkg.Stub) {
	if stub.File == "" {
		return
	}

	fmt.Fprintf(buf, "\n%s%s:%d:%d\n", linePrefix, stub.File, stub.Line, stub.Column)
}

// DropLineDirectives blanks every line directive in src.
//
// Google Wire copies the directive that Derive wrote into its own output. A
// position read from that output would name the stub file, at a line that the
// stub file does not hold. Google Wire writes one statement for each component.
// The declaration that the directive points to holds three lines.
//
// DropLineDirectives reads the scanned tokens, so a line inside a string
// literal keeps the characters that it has. Go applies only a directive that
// starts at column 1. A comment that carries the prefix at any other column is
// ordinary text.
//
// Each directive becomes a comment of its own width, so every offset and every
// line number in src keeps the value that it had.
func DropLineDirectives(src []byte) []byte {
	fset := token.NewFileSet()
	file := fset.AddFile("", fset.Base(), len(src))

	var sc scanner.Scanner
	sc.Init(file, src, nil, scanner.ScanComments)

	out := bytes.Clone(src)

	for {
		pos, tok, lit := sc.Scan()
		if tok == token.EOF {
			break
		}

		if tok != token.COMMENT || !strings.HasPrefix(lit, linePrefix) {
			continue
		}

		offset := file.Offset(pos)
		if offset > 0 && out[offset-1] != '\n' {
			continue
		}

		blank(out[offset : offset+len(lit)])
	}

	return out
}

// blank turns one directive into a comment of the same width.
func blank(directive []byte) {
	for i := range directive {
		directive[i] = ' '
	}

	copy(directive, "//")
}

// Diagnostics returns what a run prints from what Google Wire logged.
//
// It leaves out the line that names a file that Google Wire wrote. That file is
// transient, and a run takes it back out of the package. The line therefore
// states something that is no longer true.
//
// It removes Yama's own prefix from the injector name that Google Wire reports.
// The diagnostic therefore names the stub that a person wrote. Every other text
// on the line keeps the characters that it has. This includes a path with the
// same prefix.
func Diagnostics(logged string) string {
	var kept []string

	for _, line := range strings.Split(logged, "\n") {
		if strings.Contains(line, wroteMarker) {
			continue
		}

		kept = append(kept, injectorName(line))
	}

	joined := strings.Join(kept, "\n")

	return strings.TrimSpace(joined)
}

// injectorName removes Yama's own prefix from the injector name in one line. A
// line that names no injector keeps the characters that it has.
func injectorName(line string) string {
	marker := injectMarker + derivedPrefix

	head, tail, found := strings.Cut(line, marker)
	if !found {
		return line
	}

	return head + injectMarker + tail
}

// tagSeparator reports whether r stands between two build tags.
func tagSeparator(r rune) bool {
	return r == ',' || unicode.IsSpace(r)
}

// fieldList prints one parameter or result list.
func fieldList(fields []pkg.Field) string {
	printed := make([]string, 0, len(fields))

	for _, f := range fields {
		if f.Name == "" {
			printed = append(printed, f.Type)

			continue
		}

		printed = append(printed, f.Name+" "+f.Type)
	}

	return strings.Join(printed, ", ")
}
