// Code generated by Yama. DO NOT EDIT.

//go:build !yamainject

package single

import (
	yama "l7e.io/yama/v2"
	"l7e.io/yama/v2/rt"
)

// NewLifecycle orchestrates a graph of one component.
func NewLifecycle(opts ...yama.Option) (*Only, yama.Lifecycle, error) {
	only := NewOnly()

	return only,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(only).
			Build(),
		nil
}
