// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package resultcleanup

// InitApp's returned value comes from a provider that also returns a cleanup, so
// that cleanup pairs with the component the return is bound to.
func InitApp() (*App, func()) {
	dep := NewDep()
	app, cleanup := NewApp(dep)
	return app, func() {
		cleanup()
	}
}
