// Code generated by Yama. DO NOT EDIT.

//go:build !yamainject

package fanout

import (
	yama "l7e.io/yama/v2"
	"l7e.io/yama/v2/rt"
)

// NewLifecycle orchestrates a base with four independent leaves.
func NewLifecycle(opts ...yama.Option) (*Hub, yama.Lifecycle, error) {
	base := NewBase()
	leaf1 := NewLeaf1(base)
	leaf2 := NewLeaf2(base)
	leaf3 := NewLeaf3(base)
	leaf4 := NewLeaf4(base)
	hub := &Hub{
		Leaf1: leaf1,
		Leaf2: leaf2,
		Leaf3: leaf3,
		Leaf4: leaf4,
	}

	return hub,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(base).
			NextLevel().
			WithComponents(leaf1).
			WithComponents(leaf2).
			WithComponents(leaf3).
			WithComponents(leaf4).
			Build(),
		nil
}
