// Package emit assembles the lifecycle file and writes it. Every input is
// data, so emit needs no Go toolchain and no Google Wire run.
package emit

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

// BaseFileName is the name that emit writes when a run sets no prefix.
const BaseFileName = "lifecycle_gen.go"

const (
	generatedHeader   = "// Code generated by Yama. DO NOT EDIT."
	generateDirective = "//go:generate go tool yama"

	// buildConstraint keeps the lifecycle file out of the load that reads the
	// stub, so the two never declare the same constructor at once.
	buildConstraint = "//go:build !yamainject"
)

// fileMode is the mode that emit asks for the lifecycle file it writes. The
// umask of the run applies to it, and a file already in the package keeps the
// mode it carries.
//
// The lifecycle file is committed source that every build reads, so it takes
// the mode that the other files of the package take. The transient files that a
// run writes and removes take a mode of their own.
const fileMode = 0o666

// A Package is everything the lifecycle file of one target package holds.
//
// Yama and Rt are the names that the file refers to Yama's own two packages by.
// The file shares a block with the package it sits in and a scope with each
// constructor's parameters, so a name that either one holds is a name these two
// cannot take. A caller that leaves them empty gets the plain names.
type Package struct {
	Name         string
	Imports      []Import
	Constructors []Constructor

	Yama string
	Rt   string
}

// yamaName returns the name that the file refers to Yama's public package by.
func (p *Package) yamaName() string {
	if p.Yama == "" {
		return "yama"
	}

	return p.Yama
}

// rtName returns the name that the file refers to Yama's runtime package by.
func (p *Package) rtName() string {
	if p.Rt == "" {
		return "rt"
	}

	return p.Rt
}

// An Import is one entry of the import block. An empty Name means the last
// element of Path already names the package.
type Import struct {
	Name string
	Path string
}

// A Constructor is one lifecycle function. Doc is the comment above it, and it
// carries no comment markers.
//
// Statements is the construction that Google Wire performed, one entry for each
// line. Result names the value the constructor returns first. Levels holds the
// members of each lifecycle level, in the order a run starts them.
type Constructor struct {
	Doc        string
	Signature  string
	Statements []string
	Result     string
	Levels     [][]Member

	// Opts names the parameter that carries the run's options. It is empty
	// when the stub declared none, and the builder then takes nothing.
	Opts string
}

// A Member is one component's place in a level.
//
// Cleanup names the cleanup function that this component's provider returned,
// and it is empty when the provider returned none. Capable reports whether the
// component's type declares a lifecycle capability.
type Member struct {
	Name    string
	Cleanup string
	Capable bool
}

// The packages that every lifecycle file uses.
const (
	yamaPath = "l7e.io/yama/v2"
	rtPath   = "l7e.io/yama/v2/rt"
)

// runtimeImports are the packages that every lifecycle file uses, under the
// names that this file refers to them by. Render adds them, so no caller has to
// remember them.
func runtimeImports(p *Package) []Import {
	return []Import{
		{Name: p.yamaName(), Path: yamaPath},
		{Name: p.rtName(), Path: rtPath},
	}
}

// FileName returns the name that a run writes for the given output-file prefix.
func FileName(prefix string) string {
	return prefix + BaseFileName
}

// Render assembles the lifecycle file. header holds the bytes of the file that
// -header_file names, and it is nil when the run set no such flag. Render
// writes those bytes above Yama's own provenance line.
//
// Render panics when go/format rejects what it assembled. Every such failure is
// a bug in Render itself.
//
//nolint:gocritic // a Package is one whole lifecycle file, and a run renders one per target package.
func Render(p Package, header []byte) []byte {
	var body bytes.Buffer

	body.WriteString("package " + p.Name + "\n")

	rt := p.rtName()

	for i := range p.Constructors {
		writeConstructor(&body, &p.Constructors[i], rt)
	}

	var buf bytes.Buffer

	if len(header) > 0 {
		buf.Write(header)

		if !bytes.HasSuffix(header, []byte("\n")) {
			buf.WriteString("\n")
		}

		buf.WriteString("\n")
	}

	buf.WriteString(generatedHeader + "\n\n")
	buf.WriteString(generateDirective + "\n")
	buf.WriteString(buildConstraint + "\n\n")
	buf.WriteString("package " + p.Name + "\n")

	used := qualifiers(body.Bytes())
	writeImports(&buf, needed(withRuntime(&p), used))

	for i := range p.Constructors {
		writeConstructor(&buf, &p.Constructors[i], rt)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		panic(fmt.Sprintf("emit: go/format rejected the rendered file: %v\n%s", err, buf.String()))
	}

	return src
}

// qualifiers returns every name that body uses to qualify a selection, which is
// every package name the rendered code refers to.
//
// qualifiers reads the parsed source rather than the text, so neither a doc
// comment nor a field of a local value reads as a package.
func qualifiers(body []byte) map[string]bool {
	used := make(map[string]bool)

	file, err := parser.ParseFile(token.NewFileSet(), "body.go", body, 0)
	if err != nil {
		return used
	}

	ast.Inspect(file, func(n ast.Node) bool {
		sel, ok := n.(*ast.SelectorExpr)
		if !ok {
			return true
		}

		if ident, ok := sel.X.(*ast.Ident); ok {
			used[ident.Name] = true
		}

		return true
	})

	return used
}

// needed returns the imports that the rendered code refers to. An import that
// nothing refers to does not reach the file, because Go rejects a file that
// imports a package it never uses.
func needed(imports []Import, used map[string]bool) []Import {
	out := make([]Import, 0, len(imports))

	for _, imp := range imports {
		if used[packageName(imp)] {
			out = append(out, imp)
		}
	}

	return out
}

// packageName is the name that the file refers to an import by. It is the alias
// when the import declares one. Otherwise it is the last element of the path,
// and the element before a major-version element.
//
// A path whose package name is neither of those must carry an alias. Render
// writes the file it assembled without type-checking it, so it cannot read the
// name from the package itself.
func packageName(imp Import) string {
	if imp.Name != "" {
		return imp.Name
	}

	elems := strings.Split(imp.Path, "/")

	last := elems[len(elems)-1]
	if len(elems) > 1 && majorVersion(last) {
		return elems[len(elems)-2]
	}

	return last
}

// majorVersion reports whether an import path element names a major version,
// which is a "v" and then one or more digits.
func majorVersion(elem string) bool {
	digits, ok := strings.CutPrefix(elem, "v")
	if !ok || digits == "" {
		return false
	}

	for _, r := range digits {
		if r < '0' || r > '9' {
			return false
		}
	}

	return true
}

// Write puts content at name in dir, and it returns the path that it wrote.
func Write(dir, name string, content []byte) (string, error) {
	path := filepath.Join(dir, name)

	if err := os.WriteFile(path, content, fileMode); err != nil {
		return "", fmt.Errorf("write %s in %s: %w", name, dir, err)
	}

	return path, nil
}

// withRuntime adds the packages that every lifecycle file uses, under the names
// that Render writes them by. It drops a caller's import of either path, so the
// name in the import block always matches the name in the code.
func withRuntime(p *Package) []Import {
	imports := p.Imports
	runtime := runtimeImports(p)

	mine := make(map[string]bool, len(runtime))
	for _, imp := range runtime {
		mine[imp.Path] = true
	}

	out := make([]Import, 0, len(imports)+len(runtime))

	for _, imp := range imports {
		if !mine[imp.Path] {
			out = append(out, imp)
		}
	}

	return append(out, runtime...)
}

// writeImports assembles the import block. Standard-library paths come first,
// and a blank line separates them from the rest.
func writeImports(buf *bytes.Buffer, imports []Import) {
	if len(imports) == 0 {
		return
	}

	var std, other []Import

	for _, imp := range imports {
		if isStdlib(imp.Path) {
			std = append(std, imp)

			continue
		}

		other = append(other, imp)
	}

	buf.WriteString("\nimport (\n")
	writeImportGroup(buf, std)

	if len(std) > 0 && len(other) > 0 {
		buf.WriteString("\n")
	}

	writeImportGroup(buf, other)
	buf.WriteString(")\n")
}

// writeImportGroup writes one run of import lines. A line carries a name only
// when the last element of the path is not that name.
func writeImportGroup(buf *bytes.Buffer, imports []Import) {
	for _, imp := range imports {
		buf.WriteString("\t")

		if imp.Name != "" && imp.Name != lastElement(imp.Path) {
			buf.WriteString(imp.Name + " ")
		}

		buf.WriteString(strconv(imp.Path) + "\n")
	}
}

// lastElement returns the last element of an import path.
func lastElement(path string) string {
	elems := strings.Split(path, "/")

	return elems[len(elems)-1]
}

// writeConstructor writes the doc comment, the signature, the construction that
// Google Wire performed, and the lifecycle that the levels describe.
func writeConstructor(buf *bytes.Buffer, c *Constructor, rt string) {
	buf.WriteString("\n")

	if c.Doc != "" {
		for _, line := range strings.Split(c.Doc, "\n") {
			buf.WriteString("// " + line + "\n")
		}
	}

	buf.WriteString(c.Signature + " {\n")

	// Each line goes in at the left margin, and go/format lays the body out.
	// A tab of emit's own would reach the inside of a raw string literal, which
	// go/format leaves as it stands.
	for _, line := range c.Statements {
		buf.WriteString(line + "\n")
	}

	writeLifecycle(buf, c, rt)
	buf.WriteString("}\n")
}

// writeLifecycle writes the return, which hands back the built value, the
// lifecycle that the builder assembled, and a nil error.
func writeLifecycle(buf *bytes.Buffer, c *Constructor, rt string) {
	forwarded := ""
	if c.Opts != "" {
		forwarded = c.Opts + "..."
	}

	buf.WriteString("\n\treturn " + c.Result + ",\n")
	buf.WriteString("\t\t" + rt + ".NewLifecycleBuilder(" + forwarded + ").\n")

	for _, level := range c.Levels {
		buf.WriteString("\t\t\tNextLevel().\n")
		writeLevel(buf, level)
	}

	buf.WriteString("\t\t\tBuild(),\n")
	buf.WriteString("\t\tnil\n")
}

// writeLevel writes the builder calls of one level, one call for each member
// and in the order the level holds them. A member takes one of three calls:
//
//	cleanup   capability   call
//	no        any          WithComponents
//	yes       yes          WithCleanableComponent
//	yes       no           WithCleanup
func writeLevel(buf *bytes.Buffer, level []Member) {
	for _, m := range level {
		buf.WriteString("\t\t\t" + memberCall(m) + ".\n")
	}
}

// memberCall is the builder call that adds one member.
func memberCall(m Member) string {
	if m.Cleanup == "" {
		return "WithComponents(" + m.Name + ")"
	}

	if m.Capable {
		return "WithCleanableComponent(" + m.Name + ", " + m.Cleanup + ")"
	}

	return "WithCleanup(" + m.Cleanup + ")"
}

// isStdlib reports whether path names a standard-library package. A path whose
// first element holds no dot is in the standard library.
func isStdlib(path string) bool {
	first, _, _ := strings.Cut(path, "/")

	return !strings.Contains(first, ".")
}

// strconv quotes an import path.
func strconv(path string) string {
	return `"` + path + `"`
}
