// Copyright (c) 2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package emit_test

import (
	"os"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"

	"l7e.io/yama/v2/internal/generator/sketch/emit"
	"l7e.io/yama/v2/internal/generator/sketch/pkg"
)

// simple is one target package with one constructor. Most specs render it and
// then check one property of what came back.
func simple() emit.Package {
	return emit.Package{
		Name: "app",
		Imports: []pkg.Import{
			{Path: "context"},
			{Path: "example.com/app/lib"},
		},
		Constructors: []emit.Constructor{
			{
				Doc:        "NewAppLifecycle builds the lifecycle of app.",
				Signature:  "func NewAppLifecycle(ctx context.Context, opts ...yama.Option) (*lib.App, yama.Lifecycle, error)",
				Statements: []string{"app := lib.NewApp(ctx)"},
				Result:     "app",
				Levels:     [][]emit.Member{{{Name: "app", Capable: true}}},
				Opts:       "opts",
			},
		},
	}
}

var _ = Describe("emit", func() {
	Describe("FileName", func() {
		It("returns the plain name when the run set no prefix", func() {
			Expect(emit.FileName("")).To(Equal("lifecycle_gen.go"))
		})

		It("starts the name with the run's prefix", func() {
			Expect(emit.FileName("foo_")).To(Equal("foo_lifecycle_gen.go"))
		})
	})

	Describe("Render", func() {
		It("assembles a file that go/format accepts", func() {
			Expect(string(emit.Render(simple(), nil))).To(Equal(`// Code generated by Yama. DO NOT EDIT.

//go:generate go tool yama
//go:build !yamainject

package app

import (
	"context"

	"example.com/app/lib"
	yama "l7e.io/yama/v2"
	"l7e.io/yama/v2/rt"
)

// NewAppLifecycle builds the lifecycle of app.
func NewAppLifecycle(ctx context.Context, opts ...yama.Option) (*lib.App, yama.Lifecycle, error) {
	app := lib.NewApp(ctx)

	return app,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(app).
			Build(),
		nil
}
`))
		})

		Context("the provenance line", func() {
			It("names Yama and forbids an edit", func() {
				Expect(string(emit.Render(simple(), nil))).To(HavePrefix("// Code generated by Yama. DO NOT EDIT."))
			})

			It("carries the directive that regenerates the file", func() {
				Expect(string(emit.Render(simple(), nil))).To(ContainSubstring("//go:generate go tool yama"))
			})
		})

		Context("the header file", func() {
			It("writes the header above Yama's own provenance line", func() {
				rendered := string(emit.Render(simple(), []byte("// Copyright the authors.\n")))

				Expect(rendered).To(HavePrefix("// Copyright the authors.\n\n// Code generated by Yama."))
			})

			It("ends the header with a newline that the caller left off", func() {
				rendered := string(emit.Render(simple(), []byte("// Copyright the authors.")))

				Expect(rendered).To(HavePrefix("// Copyright the authors.\n\n// Code generated by Yama."))
			})

			It("writes no header when the run set no header file", func() {
				Expect(string(emit.Render(simple(), nil))).NotTo(ContainSubstring("Copyright"))
			})
		})

		Context("the import block", func() {
			It("puts the standard library above everything else", func() {
				rendered := string(emit.Render(simple(), nil))

				Expect(rendered).To(ContainSubstring("\t\"context\"\n\n\t\"example.com/app/lib\"\n"))
			})

			It("writes the name of an aliased import", func() {
				p := simple()
				p.Imports = []pkg.Import{{Name: "applib", Path: "example.com/app/lib"}}
				p.Constructors[0].Statements = []string{"app := applib.NewApp()"}

				Expect(string(emit.Render(p, nil))).To(ContainSubstring(`applib "example.com/app/lib"`))
			})

			It("leaves out an import that the constructor never refers to", func() {
				p := simple()
				p.Imports = append(p.Imports, pkg.Import{Path: "example.com/unused"})

				Expect(string(emit.Render(p, nil))).NotTo(ContainSubstring("example.com/unused"))
			})

			It("keeps a module path whose last element is a major version", func() {
				p := simple()
				p.Imports = []pkg.Import{{Path: "example.com/app/lib/v3"}}
				p.Constructors[0].Statements = []string{"app := lib.NewApp()"}

				Expect(string(emit.Render(p, nil))).To(ContainSubstring(`"example.com/app/lib/v3"`))
			})

			It("adds the runtime packages that every lifecycle file uses", func() {
				p := simple()
				p.Imports = nil

				rendered := string(emit.Render(p, nil))

				Expect(rendered).To(ContainSubstring(`yama "l7e.io/yama/v2"`))
				Expect(rendered).To(ContainSubstring(`"l7e.io/yama/v2/rt"`))
			})

			It("names a runtime package itself, whatever the caller called it", func() {
				p := simple()
				p.Imports = append(p.Imports, pkg.Import{Name: "runtime", Path: "l7e.io/yama/v2/rt"})

				rendered := string(emit.Render(p, nil))

				Expect(rendered).NotTo(ContainSubstring(`runtime "l7e.io/yama/v2/rt"`))
				Expect(rendered).To(ContainSubstring(`"l7e.io/yama/v2/rt"`))
			})
		})

		Context("a constructor", func() {
			It("writes the doc comment above the signature", func() {
				rendered := string(emit.Render(simple(), nil))

				Expect(rendered).To(ContainSubstring("// NewAppLifecycle builds the lifecycle of app.\nfunc NewAppLifecycle("))
			})

			It("writes no comment markers for a constructor that has no doc", func() {
				p := simple()
				p.Constructors[0].Doc = ""

				Expect(string(emit.Render(p, nil))).NotTo(ContainSubstring("//\n"))
			})

			It("writes one constructor for each entry", func() {
				p := simple()
				p.Constructors = append(p.Constructors, emit.Constructor{
					Signature:  "func NewOther(opts ...yama.Option) (*lib.App, yama.Lifecycle, error)",
					Statements: []string{"other := lib.NewOther()"},
					Result:     "other",
				})

				rendered := string(emit.Render(p, nil))

				Expect(rendered).To(ContainSubstring("func NewAppLifecycle("))
				Expect(rendered).To(ContainSubstring("func NewOther("))
			})

			It("indents construction of several lines", func() {
				p := simple()
				p.Constructors[0].Statements = []string{
					"db, err := lib.NewDB()",
					"if err != nil {",
					"return nil, nil, err",
					"}",
					"app := lib.NewApp(db)",
				}

				rendered := string(emit.Render(p, nil))

				Expect(rendered).To(ContainSubstring("\tdb, err := lib.NewDB()\n"))
				Expect(rendered).To(ContainSubstring("\t\treturn nil, nil, err\n"))
			})

			It("forwards the run's options through the name the stub bound", func() {
				p := simple()
				p.Constructors[0].Opts = "o"

				Expect(string(emit.Render(p, nil))).To(ContainSubstring("rt.NewLifecycleBuilder(o...)."))
			})

			It("gives the builder nothing when the stub declared no options", func() {
				p := simple()
				p.Constructors[0].Opts = ""

				Expect(string(emit.Render(p, nil))).To(ContainSubstring("rt.NewLifecycleBuilder()."))
			})

			It("writes one level of the builder for each lifecycle level", func() {
				p := simple()
				p.Constructors[0].Levels = [][]emit.Member{
					{{Name: "db", Capable: true}},
					{{Name: "repo", Capable: true}, {Name: "cache", Capable: true}},
				}

				rendered := string(emit.Render(p, nil))

				Expect(rendered).To(ContainSubstring("WithComponents(db)."))
				Expect(rendered).To(ContainSubstring("WithComponents(repo).\n\t\t\tWithComponents(cache)."))
			})

			It("pairs a capable component with the cleanup its provider returned", func() {
				p := simple()
				p.Constructors[0].Levels = [][]emit.Member{
					{{Name: "db", Cleanup: "dbCleanup", Capable: true}},
				}

				Expect(string(emit.Render(p, nil))).To(ContainSubstring("WithCleanableComponent(db, dbCleanup)."))
			})

			It("adds the cleanup alone when the component declares no capability", func() {
				p := simple()
				p.Constructors[0].Levels = [][]emit.Member{
					{{Name: "db", Cleanup: "dbCleanup"}},
				}

				rendered := string(emit.Render(p, nil))

				Expect(rendered).To(ContainSubstring("WithCleanup(dbCleanup)."))
				Expect(rendered).NotTo(ContainSubstring("db,"))
			})

			It("writes one call for each member of a level that mixes the three", func() {
				p := simple()
				p.Constructors[0].Levels = [][]emit.Member{{
					{Name: "base1", Capable: true},
					{Name: "base2", Cleanup: "base2Cleanup"},
					{Name: "base3", Cleanup: "base3Cleanup", Capable: true},
				}}

				Expect(string(emit.Render(p, nil))).To(ContainSubstring(
					"\t\t\tWithComponents(base1).\n" +
						"\t\t\tWithCleanup(base2Cleanup).\n" +
						"\t\t\tWithCleanableComponent(base3, base3Cleanup).\n"))
			})
		})
	})

	Describe("Write", func() {
		var dir string

		BeforeEach(func() {
			dir = GinkgoT().TempDir()
		})

		It("puts the content at the name it was given", func() {
			_, err := emit.Write(dir, "lifecycle_gen.go", []byte("package app\n"))
			Expect(err).NotTo(HaveOccurred())

			b, err := os.ReadFile(filepath.Join(dir, "lifecycle_gen.go"))
			Expect(err).NotTo(HaveOccurred())
			Expect(string(b)).To(Equal("package app\n"))
		})

		It("returns the path that it wrote", func() {
			path, err := emit.Write(dir, "lifecycle_gen.go", []byte("package app\n"))

			Expect(err).NotTo(HaveOccurred())
			Expect(path).To(Equal(filepath.Join(dir, "lifecycle_gen.go")))
		})

		It("writes over a file that already holds the name", func() {
			_, err := emit.Write(dir, "lifecycle_gen.go", []byte("first\n"))
			Expect(err).NotTo(HaveOccurred())

			_, err = emit.Write(dir, "lifecycle_gen.go", []byte("package app\n"))
			Expect(err).NotTo(HaveOccurred())

			b, err := os.ReadFile(filepath.Join(dir, "lifecycle_gen.go"))
			Expect(err).NotTo(HaveOccurred())
			Expect(string(b)).To(Equal("package app\n"))
		})

		// The lifecycle file is committed source that every build reads. It takes
		// the mode that an ordinary source file of the package takes, which the
		// umask of the run decides, and not a mode of its own.
		It("asks for the mode that an ordinary source file takes", func() {
			reference := filepath.Join(dir, "reference.go")

			//nolint:gosec // the mode is the one an ordinary source file carries, which is what this compares against.
			Expect(os.WriteFile(reference, []byte("package app\n"), 0o666)).To(Succeed())

			path, err := emit.Write(dir, "lifecycle_gen.go", []byte("package app\n"))
			Expect(err).NotTo(HaveOccurred())

			want, err := os.Stat(reference)
			Expect(err).NotTo(HaveOccurred())

			got, err := os.Stat(path)
			Expect(err).NotTo(HaveOccurred())

			Expect(got.Mode()).To(Equal(want.Mode()))
		})

		It("reports a directory it cannot write to", func() {
			_, err := emit.Write(filepath.Join(dir, "absent"), "lifecycle_gen.go", []byte("package app\n"))

			Expect(err).To(MatchError(ContainSubstring("lifecycle_gen.go")))
		})
	})
})
