// Copyright (c) 2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Package emit assembles the lifecycle file. It then writes that file. Every
// input is data, so emit needs no Go toolchain and no Google Wire run.
package emit

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"strings"

	"l7e.io/yama/v2/internal/generator/sketch/pkg"
)

// BaseFileName is the name that emit writes when a run sets no prefix.
const BaseFileName = "lifecycle_gen.go"

const (
	generatedHeader   = "// Code generated by Yama. DO NOT EDIT."
	generateDirective = "//go:generate go tool yama"

	// buildConstraint keeps the lifecycle file out of the load that reads the
	// stub. The two files therefore never declare the same constructor at the
	// same time.
	buildConstraint = "//go:build !yamainject"
)

// fileMode is the mode that emit asks for the lifecycle file that it writes.
// The umask of the run applies to that mode. A file that is already in the
// package keeps the mode that it carries.
//
// The lifecycle file is committed source that every build reads. It therefore
// takes the mode that the other files of the package take. The transient files
// that a run writes and removes take a mode of their own.
const fileMode = 0o666

// A Package is everything that the lifecycle file of one target package holds.
//
// Yama and Rt are the names that the file uses for Yama's own two packages. The
// file shares a block with the package that contains it. It also shares a scope
// with each constructor's parameters. Yama and Rt cannot take a name that the
// block or a scope holds. A caller that leaves Yama and Rt empty gets the plain
// names.
type Package struct {
	Name         string
	Imports      []pkg.Import
	Constructors []Constructor

	Yama string
	Rt   string
}

// yamaName returns the name that the file uses for Yama's public package.
func (p *Package) yamaName() string {
	if p.Yama == "" {
		return "yama"
	}

	return p.Yama
}

// rtName returns the name that the file uses for Yama's runtime package.
func (p *Package) rtName() string {
	if p.Rt == "" {
		return "rt"
	}

	return p.Rt
}

// A Constructor is one lifecycle function. Doc is the comment above that
// function. Doc carries no comment markers.
//
// Statements is the construction that Google Wire performed, one entry for each
// line. Result names the value that the constructor returns first. Levels holds
// the members of each lifecycle level, in the order that a run starts them.
type Constructor struct {
	Doc        string
	Signature  string
	Statements []string
	Result     string
	Levels     [][]Member

	// Opts names the parameter that carries the run's options. Opts is empty
	// when the stub declared no options. The builder then takes no argument.
	Opts string
}

// A Member is one component's place in a level.
//
// Cleanup names the cleanup function that this component's provider returned.
// Cleanup is empty when the provider returned no cleanup function. Capable
// reports whether the component's type declares a lifecycle capability.
type Member struct {
	Name    string
	Cleanup string
	Capable bool
}

// These are the packages that every lifecycle file uses.
const (
	yamaPath = "l7e.io/yama/v2"
	rtPath   = "l7e.io/yama/v2/rt"
)

// runtimeImports are the packages that every lifecycle file uses, under the
// names that this file uses for them. Render adds them, so no caller has to
// remember them.
func runtimeImports(p *Package) []pkg.Import {
	return []pkg.Import{
		{Name: p.yamaName(), Path: yamaPath},
		{Name: p.rtName(), Path: rtPath},
	}
}

// FileName returns the name that a run writes for the given output-file prefix.
func FileName(prefix string) string {
	return prefix + BaseFileName
}

// Render assembles the lifecycle file. header holds the bytes of the file that
// -header_file names. header is nil when the run set no such flag. Render
// writes those bytes above Yama's own provenance line.
//
// Render panics when go/format rejects what it assembled. Every such failure is
// a bug in Render itself.
//
//nolint:gocritic // a Package is one whole lifecycle file, and a run renders one per target package.
func Render(p Package, header []byte) []byte {
	var body bytes.Buffer

	body.WriteString("package " + p.Name + "\n")

	rt := p.rtName()

	for i := range p.Constructors {
		writeConstructor(&body, &p.Constructors[i], rt)
	}

	var buf bytes.Buffer

	if len(header) > 0 {
		buf.Write(header)

		if !bytes.HasSuffix(header, []byte("\n")) {
			buf.WriteString("\n")
		}

		buf.WriteString("\n")
	}

	buf.WriteString(generatedHeader + "\n\n")
	buf.WriteString(generateDirective + "\n")
	buf.WriteString(buildConstraint + "\n\n")
	buf.WriteString("package " + p.Name + "\n")

	used := pkg.Qualifiers(body.Bytes())
	writeImports(&buf, needed(withRuntime(&p), used))

	for i := range p.Constructors {
		writeConstructor(&buf, &p.Constructors[i], rt)
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		panic(fmt.Sprintf("emit: go/format rejected the rendered file: %v\n%s", err, buf.String()))
	}

	return src
}

// needed returns the imports that the rendered code refers to. An import that
// nothing refers to does not reach the file, because Go rejects a file that
// imports a package that it never uses.
func needed(block []pkg.Import, used map[string]bool) []pkg.Import {
	out := make([]pkg.Import, 0, len(block))

	for _, imp := range block {
		name := pkg.PackageName(imp.Name, imp.Path)

		if used[name] {
			out = append(out, imp)
		}
	}

	return out
}

// Write puts content at name in dir. It returns the path that it wrote.
func Write(dir, name string, content []byte) (string, error) {
	path := filepath.Join(dir, name)

	if err := os.WriteFile(path, content, fileMode); err != nil {
		return "", fmt.Errorf("write %s in %s: %w", name, dir, err)
	}

	return path, nil
}

// withRuntime adds the packages that every lifecycle file uses, under the names
// that Render uses for them. It drops a caller's import of either path, so the
// name in the import block always matches the name in the code.
func withRuntime(p *Package) []pkg.Import {
	stated := p.Imports
	runtime := runtimeImports(p)

	mine := make(map[string]bool, len(runtime))
	for _, imp := range runtime {
		mine[imp.Path] = true
	}

	out := make([]pkg.Import, 0, len(stated)+len(runtime))

	for _, imp := range stated {
		if !mine[imp.Path] {
			out = append(out, imp)
		}
	}

	return append(out, runtime...)
}

// writeImports assembles the import block. Standard-library paths come first.
// A blank line separates them from the other paths.
func writeImports(buf *bytes.Buffer, block []pkg.Import) {
	if len(block) == 0 {
		return
	}

	var std, other []pkg.Import

	for _, imp := range block {
		if isStdlib(imp.Path) {
			std = append(std, imp)

			continue
		}

		other = append(other, imp)
	}

	buf.WriteString("\nimport (\n")
	writeImportGroup(buf, std)

	if len(std) > 0 && len(other) > 0 {
		buf.WriteString("\n")
	}

	writeImportGroup(buf, other)
	buf.WriteString(")\n")
}

// writeImportGroup writes one run of import lines. A line carries a name only
// when the last element of the path is not that name.
func writeImportGroup(buf *bytes.Buffer, block []pkg.Import) {
	for _, imp := range block {
		buf.WriteString("\t")

		if imp.Name != "" && imp.Name != lastElement(imp.Path) {
			buf.WriteString(imp.Name + " ")
		}

		buf.WriteString(strconv(imp.Path) + "\n")
	}
}

// lastElement returns the last element of an import path.
func lastElement(path string) string {
	elems := strings.Split(path, "/")

	return elems[len(elems)-1]
}

// writeConstructor writes the doc comment, the signature, the construction that
// Google Wire performed, and the lifecycle that the levels describe.
func writeConstructor(buf *bytes.Buffer, c *Constructor, rt string) {
	buf.WriteString("\n")

	if c.Doc != "" {
		for _, line := range strings.Split(c.Doc, "\n") {
			buf.WriteString("// " + line + "\n")
		}
	}

	buf.WriteString(c.Signature + " {\n")

	// Each line goes in at the left margin, and go/format indents the body.
	// A tab of emit's own would reach the inside of a raw string literal.
	// go/format makes no change to such a literal.
	for _, line := range c.Statements {
		buf.WriteString(line + "\n")
	}

	writeLifecycle(buf, c, rt)
	buf.WriteString("}\n")
}

// writeLifecycle writes the return statement. That statement returns the built
// value, the lifecycle that the builder assembled, and a nil error.
func writeLifecycle(buf *bytes.Buffer, c *Constructor, rt string) {
	forwarded := ""
	if c.Opts != "" {
		forwarded = c.Opts + "..."
	}

	buf.WriteString("\n\treturn " + c.Result + ",\n")
	buf.WriteString("\t\t" + rt + ".NewLifecycleBuilder(" + forwarded + ").\n")

	for _, level := range c.Levels {
		buf.WriteString("\t\t\tNextLevel().\n")
		writeLevel(buf, level)
	}

	buf.WriteString("\t\t\tBuild(),\n")
	buf.WriteString("\t\tnil\n")
}

// writeLevel writes the builder calls of one level, one call for each member
// and in the order that the level holds them. A member takes one of three
// calls:
//
//	cleanup   capability   call
//	no        any          WithComponents
//	yes       yes          WithCleanableComponent
//	yes       no           WithCleanup
func writeLevel(buf *bytes.Buffer, level []Member) {
	for _, m := range level {
		buf.WriteString("\t\t\t" + memberCall(m) + ".\n")
	}
}

// memberCall is the builder call that adds one member.
func memberCall(m Member) string {
	if m.Cleanup == "" {
		return "WithComponents(" + m.Name + ")"
	}

	if m.Capable {
		return "WithCleanableComponent(" + m.Name + ", " + m.Cleanup + ")"
	}

	return "WithCleanup(" + m.Cleanup + ")"
}

// isStdlib reports whether path names a standard-library package. A path is in
// the standard library if its first element holds no dot.
func isStdlib(path string) bool {
	first, _, _ := strings.Cut(path, "/")

	return !strings.Contains(first, ".")
}

// strconv quotes an import path.
func strconv(path string) string {
	return `"` + path + `"`
}
