// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package resultcollision

import (
	"example.com/app/inbound"
	"example.com/app/outbound"
)

// Two independent injectors. Each returns a result struct whose short type name
// is App, but the two App types come from different packages, so Yama's
// package-unqualified generated namespace cannot tell them apart.
func InitializeInbound() (*inbound.App, error) {
	logger := NewConsoleLogger()
	svc := inbound.NewService(logger)
	app := &inbound.App{
		Service: svc,
	}
	return app, nil
}

func InitializeOutbound() (*outbound.App, error) {
	logger := NewConsoleLogger()
	svc := outbound.NewService(logger)
	app := &outbound.App{
		Service: svc,
	}
	return app, nil
}
