// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package fieldwrite

// InitializeApp threads mid1's dependency on base2 through a field write rather
// than a constructor argument. Wire never emits this; the AST-only parser cannot
// turn a field mutation into a creation-consumption edge.
func InitializeApp() (*App, error) {
	config := _wireConfigValue
	logger := NewConsoleLogger(config)
	base2 := NewBase2(logger)
	mid1 := NewMid1(logger)
	mid1.base2 = base2
	root1 := NewRoot1(logger, mid1)
	app := &App{
		root1: root1,
	}
	return app, nil
}

var _wireConfigValue = Config{Env: Prod}
