// Code generated by Yama. DO NOT EDIT.

//go:generate go tool yama
//go:build !yamainject

package pkgscope

import (
	yama "l7e.io/yama/v2"
	rt2 "l7e.io/yama/v2/rt"
)

// NewLifecycle orchestrates a graph in a package that already declares rt.
func NewLifecycle(opts ...yama.Option) (*A, yama.Lifecycle, error) {
	a := NewA()

	return a,
		rt2.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(a).
			Build(),
		nil
}
