// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package fieldnames

// InitApp deliberately makes field names collide with component variable names:
// the composite-literal key `port` and the intermediate selector field `b` each
// match a component, yet neither is a dependency the component consumes.
func InitApp() *App {
	port := NewPort()
	cfg := NewCfg()
	a := NewA()
	b := NewB()
	h := NewH(Opts{port: cfg})
	x := a.b.c
	dup := NewDup(port, port)
	app := NewApp(h, x, dup, port, b)
	return app
}
