// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package minimal

// Injectors from wire.go:

// InitApp builds an App with no dependency-bearing providers.
func InitApp() *App {
	app := &App{}
	return app
}
