// Code generated by Yama. DO NOT EDIT.

//go:generate go tool yama
//go:build !yamainject

package testapp

import (
	yama "l7e.io/yama/v2"
	"l7e.io/yama/v2/rt"
)

// NewLifecycle orchestrates the graph GraphSet builds. The recorder collects
// what the components report, and the fault selects the component whose Start
// fails.
func NewLifecycle(rec *Recorder, fault Fault, opts ...yama.Option) (*Top, yama.Lifecycle, error) {
	res, resCleanup := NewRes(rec)
	base := NewBase(rec, fault, res)
	mid := NewMid(rec, fault, base)
	leaf, leafCleanup := NewLeaf(rec, fault, base)
	top := NewTop(rec, fault, mid, leaf)

	return top,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithCleanup(resCleanup).
			NextLevel().
			WithComponents(base).
			NextLevel().
			WithComponents(mid).
			WithCleanableComponent(leaf, leafCleanup).
			NextLevel().
			WithComponents(top).
			Build(),
		nil
}
