// Code generated by Yama. DO NOT EDIT.

//go:generate go tool yama
//go:build !yamainject

package chain

import (
	"l7e.io/yama"
	"l7e.io/yama/rt"
)

// NewLifecycle orchestrates a three-component chain.
func NewLifecycle(opts ...yama.Option) (*C, yama.Lifecycle, error) {
	a := NewA()
	b := NewB(a)
	c := NewC(b)

	return c,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(a).
			NextLevel().
			WithComponents(b).
			NextLevel().
			WithComponents(c).
			Build(),
		nil
}
