// Code generated by Yama. DO NOT EDIT.

//go:build !yamainject

package blankopts

import (
	yama "l7e.io/yama/v2"
	"l7e.io/yama/v2/rt"
)

// NewLifecycle binds the blank identifier to its options parameter, which the
// emitted constructor cannot forward under that name.
func NewLifecycle(opts ...yama.Option) (*App, yama.Lifecycle, error) {
	app := NewApp()

	return app,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(app).
			Build(),
		nil
}
