// Code generated by Yama. DO NOT EDIT.

//go:build !yamainject

package optscollision

import (
	yama2 "l7e.io/yama/v2"
	rt2 "l7e.io/yama/v2/rt"
)

// NewALifecycle names its options parameter after the runtime-support package,
// which the constructor's own body calls the builder on.
func NewALifecycle(rt ...yama2.Option) (*A, yama2.Lifecycle, error) {
	a := NewA()

	return a,
		rt2.NewLifecycleBuilder(rt...).
			NextLevel().
			WithComponents(a).
			Build(),
		nil
}

// NewBLifecycle names its options parameter after the public package, which the
// constructor's signature names.
func NewBLifecycle(yama ...yama2.Option) (*B, yama2.Lifecycle, error) {
	b := NewB()

	return b,
		rt2.NewLifecycleBuilder(yama...).
			NextLevel().
			WithComponents(b).
			Build(),
		nil
}
