// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package orphancleanup

// InitApp's aggregated cleanup closure calls orphaned, which no creation event
// binds, so the cleanup pairs with no component.
func InitApp() (*App, func()) {
	dep := NewDep()
	app := NewApp(dep)
	return app, func() {
		orphaned()
	}
}
