// Code generated by Yama. DO NOT EDIT.

//go:build !yamainject

package empty

import (
	yama "l7e.io/yama/v2"
	"l7e.io/yama/v2/rt"
)

// NewLifecycle orchestrates a graph with no level in it.
func NewLifecycle(opts ...yama.Option) (*App, yama.Lifecycle, error) {
	app := &App{}

	return app,
		rt.NewLifecycleBuilder(opts...).
			Build(),
		nil
}
