// Code generated by MockGen. DO NOT EDIT.
// Source: lifecycle.go
//
// Generated by this command:
//
//	mockgen -source=lifecycle.go -destination=../mocks/exec_mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCompleteLifecycle is a mock of CompleteLifecycle interface.
type MockCompleteLifecycle struct {
	ctrl     *gomock.Controller
	recorder *MockCompleteLifecycleMockRecorder
	isgomock struct{}
}

// MockCompleteLifecycleMockRecorder is the mock recorder for MockCompleteLifecycle.
type MockCompleteLifecycleMockRecorder struct {
	mock *MockCompleteLifecycle
}

// NewMockCompleteLifecycle creates a new mock instance.
func NewMockCompleteLifecycle(ctrl *gomock.Controller) *MockCompleteLifecycle {
	mock := &MockCompleteLifecycle{ctrl: ctrl}
	mock.recorder = &MockCompleteLifecycleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCompleteLifecycle) EXPECT() *MockCompleteLifecycleMockRecorder {
	return m.recorder
}

// Quiesce mocks base method.
func (m *MockCompleteLifecycle) Quiesce(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Quiesce", arg0)
}

// Quiesce indicates an expected call of Quiesce.
func (mr *MockCompleteLifecycleMockRecorder) Quiesce(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Quiesce", reflect.TypeOf((*MockCompleteLifecycle)(nil).Quiesce), arg0)
}

// Start mocks base method.
func (m *MockCompleteLifecycle) Start(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Start", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Start indicates an expected call of Start.
func (mr *MockCompleteLifecycleMockRecorder) Start(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Start", reflect.TypeOf((*MockCompleteLifecycle)(nil).Start), arg0)
}

// Stop mocks base method.
func (m *MockCompleteLifecycle) Stop(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Stop", arg0)
}

// Stop indicates an expected call of Stop.
func (mr *MockCompleteLifecycleMockRecorder) Stop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stop", reflect.TypeOf((*MockCompleteLifecycle)(nil).Stop), arg0)
}
