// Code generated by Yama. DO NOT EDIT.

//go:generate go tool yama
//go:build !yamainject

package noopts

import (
	"l7e.io/yama"
	"l7e.io/yama/rt"
)

// NewLifecycle orchestrates the graph NewApp builds. It takes a graph parameter
// and no options.
func NewLifecycle(cfg *Config) (*App, yama.Lifecycle, error) {
	app := NewApp(cfg)

	return app,
		rt.NewLifecycleBuilder().
			NextLevel().
			WithComponents(app).
			Build(),
		nil
}
