// Code generated by Yama. DO NOT EDIT.

//go:generate go tool yama
//go:build !yamainject

package value

import (
	"l7e.io/yama"
	"l7e.io/yama/rt"
)

// NewLifecycle orchestrates a graph whose value provider holds a multi-line raw
// string. The golden records the literal with its own lines unchanged.
func NewLifecycle(opts ...yama.Option) (*App, yama.Lifecycle, error) {
	banner := Banner(`alpha
beta
gamma`)
	app := NewApp(banner)

	return app,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(app).
			Build(),
		nil
}
