// Copyright (c) 2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generator

import (
	"bytes"
	"context"
	"io"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"l7e.io/yama/internal/generator/wire"
)

// The specs in this file start Google Wire. Every other test in the tree gives
// the run an output that takes the place of Google Wire's own. Such an
// output states nothing about whether Google Wire accepts what the run
// derives.

// requireGo skips the test when the machine has no Go toolchain.
func requireGo(t *testing.T) {
	t.Helper()

	if _, err := exec.LookPath("go"); err != nil {
		t.Skipf("go toolchain not found on PATH: %v", err)
	}
}

// quietDriver returns a Driver that writes what it did nowhere. A test that
// reads that output back assigns progress a buffer of its own instead.
func quietDriver(dir string, patterns []string, args wire.Args) *Driver {
	d := NewDriver(dir, patterns, args)
	d.progress = io.Discard

	return d
}

// A fixture is one package under testdata, named with the files that it holds.
type fixture struct {
	name  string
	files []string
}

var (
	// wirerun holds a plain graph. NewDB returns a cleanup and declares no
	// capability, and App consumes it.
	wirerun = fixture{"wirerun", []string{"components.go", "lifecycle.go"}}

	// taggedrun holds the same graph, with the one provider of *DB behind the
	// special build tag.
	taggedrun = fixture{"taggedrun", []string{"components.go", "special.go", "lifecycle.go"}}

	// badgraph holds a stub that names no provider of *DB. Google Wire rejects
	// that stub.
	badgraph = fixture{"badgraph", []string{"components.go", "lifecycle.go"}}

	// badstub holds a stub that declares two results. A lifecycle stub declares
	// three.
	badstub = fixture{"badstub", []string{"components.go", "lifecycle.go"}}

	// valuerun holds a stub with a graph that takes a wire.Value provider.
	valuerun = fixture{"valuerun", []string{"components.go", "lifecycle.go"}}

	// setrun holds a stub that names a provider set, and never the package that
	// declares the provider in that set. testdata/setlib states the set, and
	// testdata/setother declares the provider.
	setrun = fixture{"setrun", []string{"components.go", "lifecycle.go"}}
)

// copyFixture puts a copy of the fixture package in a directory of its own. It
// returns the path of that copy.
//
// The copy is under testdata, inside this module. Google Wire resolves its own
// import and the yama import against the module of the directory that it runs
// in. No directory outside this module holds either one.
func copyFixture(t *testing.T, f fixture) string {
	t.Helper()

	root, err := filepath.Abs("testdata")
	require.NoError(t, err)

	source := filepath.Join(root, f.name)

	dir, err := os.MkdirTemp(root, "run-")
	require.NoError(t, err)

	t.Cleanup(func() {
		_ = os.RemoveAll(dir)
	})

	for _, name := range f.files {
		content, readErr := os.ReadFile(filepath.Join(source, name))
		require.NoError(t, readErr)

		//nolint:gosec // name is a constant of this file, and dir is the directory that MkdirTemp just made.
		require.NoError(t, os.WriteFile(filepath.Join(dir, name), content, 0o600))
	}

	return dir
}

// TestDriverRunsGoogleWire runs one whole generation over a real package. It is
// the one test that proves Google Wire accepts the injector that wire.Derive
// wrote.
func TestDriverRunsGoogleWire(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, wirerun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})

	require.NoError(t, d.Run(context.Background()))

	content, err := os.ReadFile("lifecycle_gen.go")
	require.NoError(t, err)

	lifecycle := string(content)

	assert.Contains(t, lifecycle, "// Code generated by Yama. DO NOT EDIT.")
	signature := "func NewAppLifecycle(ctx context.Context, node *yaml.Node, opts ...yama.Option) " +
		"(*App, yama.Lifecycle, error)"

	assert.Contains(t, lifecycle, signature)
	assert.Contains(t, lifecycle, "rt.NewLifecycleBuilder(opts...)")
}

// TestDriverNamesAnImportThePathDoesNotName asserts the name that the emitted
// file gives gopkg.in/yaml.v3. That path declares the package yaml. A guess
// over the path alone produces yaml.v3, and that name names nothing.
func TestDriverNamesAnImportThePathDoesNotName(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, wirerun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})
	require.NoError(t, d.Run(context.Background()))

	content, err := os.ReadFile("lifecycle_gen.go")
	require.NoError(t, err)

	assert.Contains(t, string(content), `yaml "gopkg.in/yaml.v3"`)
}

// TestDriverEmitsTheLifecycleOfTheGraph asserts the levels and the calls that
// the graph produces. NewDB returns a cleanup and declares no capability, so
// its cleanup goes in alone. App consumes it, so App is one level behind.
func TestDriverEmitsTheLifecycleOfTheGraph(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, wirerun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})
	require.NoError(t, d.Run(context.Background()))

	content, err := os.ReadFile("lifecycle_gen.go")
	require.NoError(t, err)

	assert.Contains(t, string(content), "NextLevel().\n\t\t\tWithCleanup(dbCleanup).\n\t\t\tNextLevel().\n\t\t\tWithComponents(app).")
}

// TestDriverLeavesNoTransientFile asserts that a run takes every file that it
// wrote for Google Wire back out of the package.
func TestDriverLeavesNoTransientFile(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, wirerun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})
	require.NoError(t, d.Run(context.Background()))

	for _, name := range []string{wire.DerivedFileName, wire.PlaceholderFileName, wire.BaseOutputName} {
		_, err := os.Lstat(name)

		assert.Truef(t, os.IsNotExist(err), "%s is still in the package", name)
	}
}

// TestDriverEmitsAPackageThatCompiles builds the package that a run settled. It
// is the one test that reads the emitted file the way the Go compiler does.
func TestDriverEmitsAPackageThatCompiles(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, wirerun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})
	require.NoError(t, d.Run(context.Background()))

	build := exec.CommandContext(context.Background(), "go", "build", ".")

	out, err := build.CombinedOutput()

	require.NoErrorf(t, err, "go build rejected the emitted package:\n%s", out)
}

// TestDriverWritesTheHeaderFileAboveTheProvenanceLine runs Google Wire with the
// flag that names a header file, and it reads what reached the lifecycle file.
func TestDriverWritesTheHeaderFileAboveTheProvenanceLine(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, wirerun)
	t.Chdir(dir)

	require.NoError(t, os.WriteFile("boilerplate.txt", []byte("// Copyright the authors.\n"), 0o600))

	d := quietDriver(".", []string{"."}, wire.Args{HeaderFile: "boilerplate.txt"})
	require.NoError(t, d.Run(context.Background()))

	content, err := os.ReadFile("lifecycle_gen.go")
	require.NoError(t, err)

	assert.True(t, strings.HasPrefix(string(content), "// Copyright the authors.\n\n// Code generated by Yama."))
}

// TestDriverReadsThePackageUnderTheRunsOwnTags runs a generation over a package
// with its one provider of *DB behind the special tag. Google Wire receives
// that tag. The load that reads Google Wire's output must receive it also.
func TestDriverReadsThePackageUnderTheRunsOwnTags(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, taggedrun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{Tags: "special"})

	require.NoError(t, d.Run(context.Background()))

	content, err := os.ReadFile("lifecycle_gen.go")
	require.NoError(t, err)

	assert.Contains(t, string(content), "WithCleanup(dbCleanup)")
}

// TestDriverFailsWhenTheRunSetNoTag asserts that the same package fails without
// the tag. This test is what makes the test above state something.
func TestDriverFailsWhenTheRunSetNoTag(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, taggedrun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})

	require.Error(t, d.Run(context.Background()))
}

// TestDriverExpandsARecursivePattern drives a run with "./...". That pattern
// names no directory, and nothing outside the driver turns it into one.
func TestDriverExpandsARecursivePattern(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, wirerun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"./..."}, wire.Args{})

	require.NoError(t, d.Run(context.Background()))

	content, err := os.ReadFile("lifecycle_gen.go")
	require.NoError(t, err)

	assert.Contains(t, string(content), "rt.NewLifecycleBuilder(opts...)")
}

// TestDriverTakesNoPatternToMeanTheCurrentDirectory drives a run with no
// pattern at all. `wire gen` gives the meaning "." to no pattern.
func TestDriverTakesNoPatternToMeanTheCurrentDirectory(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, wirerun)
	t.Chdir(dir)

	d := quietDriver(".", nil, wire.Args{})

	require.NoError(t, d.Run(context.Background()))

	assert.FileExists(t, "lifecycle_gen.go")
}

// TestDriverReportsEveryLifecycleFileItWrote drives a run over one package and
// reads what the run printed. The run names the package by the import path that
// the package declares. It names the file by the file's absolute path.
func TestDriverReportsEveryLifecycleFileItWrote(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, wirerun)
	t.Chdir(dir)

	var progress bytes.Buffer

	d := NewDriver(".", []string{"."}, wire.Args{})
	d.progress = &progress

	require.NoError(t, d.Run(context.Background()))

	pkgPath := corpusPrefix + filepath.Base(dir)
	written := filepath.Join(dir, "lifecycle_gen.go")

	assert.Equal(t, "yama: "+pkgPath+": wrote "+written+"\n", progress.String())
}

// TestDriverReportsNoFileForAPackageItSkipped drives a run over a package that
// declares no lifecycle stub. The run writes no lifecycle file there, and it
// reports no file.
func TestDriverReportsNoFileForAPackageItSkipped(t *testing.T) {
	requireGo(t)

	dir := copyFamily(t, "nogen")
	t.Chdir(dir)

	var progress bytes.Buffer

	d := NewDriver(".", []string{"."}, wire.Args{})
	d.progress = &progress

	require.NoError(t, d.Run(context.Background()))

	assert.NotContains(t, progress.String(), "wrote")
}

// TestDriverGeneratesPastAPackageItCannotWriteTo drives a run over a family
// with one directory that takes no new file. That package fails. Every other
// package still takes its lifecycle file, and the failure reaches the caller.
func TestDriverGeneratesPastAPackageItCannotWriteTo(t *testing.T) {
	requireGo(t)

	if runtime.GOOS == "windows" {
		t.Skip("Windows does not apply the permission bits of a directory, so the failure cannot be staged")
	}

	if os.Geteuid() == 0 {
		t.Skip("the superuser writes to a read-only directory, so the failure cannot be staged")
	}

	dir := copyFamily(t, "multipkg")
	readOnly := filepath.Join(dir, "a")

	require.NoError(t, os.Chmod(readOnly, 0o500))

	t.Cleanup(func() {
		_ = os.Chmod(readOnly, 0o700)
	})

	t.Chdir(dir)

	d := quietDriver(".", []string{"./..."}, wire.Args{})

	require.Error(t, d.Run(context.Background()))

	assert.NoFileExists(t, filepath.Join(readOnly, "lifecycle_gen.go"))
	assert.FileExists(t, filepath.Join(dir, "b", "lifecycle_gen.go"))
}

// TestDriverReportsWireAgainstTheStubTheUserWrote drives a run over a package
// that Google Wire rejects. It reads what the run printed.
//
// Google Wire reads the file that Yama derived, and it names the injector that
// Yama invented. The user wrote neither one, and neither one survives the run.
func TestDriverReportsWireAgainstTheStubTheUserWrote(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, badgraph)
	t.Chdir(dir)

	var progress bytes.Buffer

	d := NewDriver(".", []string{"."}, wire.Args{})
	d.progress = &progress

	require.Error(t, d.Run(context.Background()))

	reported := progress.String()

	assert.Contains(t, reported, "lifecycle.go:", "names the stub file")
	assert.Contains(t, reported, "inject NewAppLifecycle", "names the stub")
	assert.NotContains(t, reported, wire.DerivedFileName, "names no transient file")
	assert.NotContains(t, reported, "inject yama_", "names no derived injector")
}

// TestDriverLeavesNoLineDirectiveInTheLifecycleFile asserts that the directive
// that Yama wrote for Google Wire reaches no committed file. Google Wire copies
// it into its own output, and Generate reads that output.
func TestDriverLeavesNoLineDirectiveInTheLifecycleFile(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, wirerun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})
	require.NoError(t, d.Run(context.Background()))

	content, err := os.ReadFile("lifecycle_gen.go")
	require.NoError(t, err)

	assert.NotContains(t, string(content), "//line ")
}

// TestDriverRejectsAStubItCannotEmitFrom drives a run over a package with a
// stub that declares the wrong results.
//
// A run that read that stub and wrote a file anyway would report success and
// leave a package that no build accepts.
func TestDriverRejectsAStubItCannotEmitFrom(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, badstub)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})

	err := d.Run(context.Background())

	require.Error(t, err)
	assert.ErrorContains(t, err, "declares 2 results")
	assert.ErrorContains(t, err, "lifecycle.go:")
	assert.NoFileExists(t, "lifecycle_gen.go")
}

// TestDriverEmitsAValueProvider drives a run over a graph that takes a
// wire.Value provider.
//
// Google Wire writes that provider as a read of a package-level variable that
// its own output declares. A run takes that output out of the package. The
// lifecycle file has to state the value itself.
func TestDriverEmitsAValueProvider(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, valuerun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})
	require.NoError(t, d.Run(context.Background()))

	content, err := os.ReadFile("lifecycle_gen.go")
	require.NoError(t, err)

	lifecycle := string(content)

	assert.Contains(t, lifecycle, `config := Config{Env: "prod"}`)
	assert.NotContains(t, lifecycle, "_wireConfigValue")
}

// TestDriverEmitsAValueProviderThatCompiles builds the package that the run
// above settled. A read of Google Wire's own variable compiles nowhere.
func TestDriverEmitsAValueProviderThatCompiles(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, valuerun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})
	require.NoError(t, d.Run(context.Background()))

	build := exec.CommandContext(context.Background(), "go", "build", ".")

	out, err := build.CombinedOutput()

	require.NoErrorf(t, err, "go build rejected the emitted package:\n%s", out)
}

// TestDriverImportsWhatTheConstructionNames drives a run over a stub that names
// a provider set. The construction that Google Wire performs calls a provider
// in a package that no stub file imports.
func TestDriverImportsWhatTheConstructionNames(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, setrun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})
	require.NoError(t, d.Run(context.Background()))

	content, err := os.ReadFile("lifecycle_gen.go")
	require.NoError(t, err)

	lifecycle := string(content)

	assert.Contains(t, lifecycle, "testdata/setother")
	assert.Contains(t, lifecycle, "thing := setother.NewThing()")
}

// TestDriverImportsWhatTheConstructionNamesAndCompiles builds the package that
// the run above settled. The construction can name an import that the file
// leaves out, and such a file compiles nowhere.
func TestDriverImportsWhatTheConstructionNamesAndCompiles(t *testing.T) {
	requireGo(t)

	dir := copyFixture(t, setrun)
	t.Chdir(dir)

	d := quietDriver(".", []string{"."}, wire.Args{})
	require.NoError(t, d.Run(context.Background()))

	build := exec.CommandContext(context.Background(), "go", "build", ".")

	out, err := build.CombinedOutput()

	require.NoErrorf(t, err, "go build rejected the emitted package:\n%s", out)
}
