// Copyright (c) 2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"path"
	"sort"
	"strconv"
	"strings"
)

// lifecycleGenName is the one file a generation run commits.
const lifecycleGenName = "lifecycle_gen.go"

// generatedHeader opens every file Yama writes, the committed lifecycle file and
// the transient derived-injector file alike, and records its provenance. Its
// exact form, trailing period included, is what the Go toolchain and the
// ecosystem's tools match a generated file on.
const generatedHeader = "// Code generated by Yama. DO NOT EDIT."

// rtPkgPath is the runtime-support package the emitted file calls the builder
// on, and rtPkgName is the name it declares.
const (
	rtPkgPath = yamaPkgPath + "/rt"
	rtPkgName = "rt"
)

// LifecycleFile is one package's emitted lifecycle file, ready to be written.
//
// Errs holds what went wrong while rendering it, and Content is set whether or
// not Errs is empty. A caller writes the content, reports the errors, and fails
// the run, which is how Google Wire reports the same kind of failure: the
// unreadable artifact is the diagnostic, so it reaches the disk rather than
// being discarded with the error.
type LifecycleFile struct {
	Dir     string
	Name    string
	Content []byte
	Errs    []error
}

// Emit renders a package's lifecycle file: one constructor per lifecycle stub,
// each re-emitting its derived injector's construction and then declaring its
// levels through the runtime-support package's builder.
//
// It reads the stub for the constructor's name and documentation, the parsed
// injector for the signature and the construction body, and the analysis for
// the levels.
//
// Emit rebinds each Google Wire cleanup in the parsed injectors it is given,
// which is the one identifier the emitted file does not take from the stub or
// from Wire.
//
// Every way Emit can fail is a Yama bug rather than a problem with the
// application's input. A mismatch it cannot render around panics: a run reaches
// Emit only after Wire succeeded, and Wire writes one injector per declaration,
// so the analysis holds one entry per stub. Source this emitter built that Go
// cannot format is reported through the returned file's Errs, with the
// unformatted source in Content.
func Emit(sp *StubPackage, pkg *LoadedPackage, analysis *Analysis) *LifecycleFile {
	constructors := pairStubs(sp, analysis)

	for _, c := range constructors {
		rebindCleanups(c.analysis.Injector)
	}

	// Ordered, so that no step has to undo an earlier one. The imports the
	// bodies refer to cannot move. The options parameters then give way to
	// those. Yama's own imports are claimed last, and give way to everything.
	imports := &importSet{paths: bodyImports(pkg, constructors)}
	scope := newFileScope(pkg, imports, constructors)
	bindOptsNames(scope, constructors)
	imports.yama = imports.claim(scope, yamaPkgName, yamaPkgPath)
	imports.rt = imports.claim(scope, rtPkgName, rtPkgPath)

	content, err := renderFile(sp, pkg, imports, constructors)

	file := &LifecycleFile{Dir: sp.Dir, Name: lifecycleGenName, Content: content}
	if err != nil {
		file.Errs = append(file.Errs, err)
	}

	return file
}

// constructor is one emitted constructor: the stub that names it beside the
// analysis of the injector derived from that stub.
//
// opts is the name the constructor binds its Option parameter to. It is the
// stub's own name, unless the re-emitted body needs that name for a package it
// refers to. It is empty when the stub declares no options parameter.
type constructor struct {
	stub     *Stub
	analysis *InjectorAnalysis
	opts     string
}

// pairStubs matches each stub with the analysis of its derived injector, in
// stub order.
func pairStubs(sp *StubPackage, analysis *Analysis) []constructor {
	constructors := make([]constructor, 0, len(sp.Stubs))
	for _, stub := range sp.Stubs {
		ia := analysis.For(stub.DerivedName())
		if ia == nil {
			panic(fmt.Sprintf("generator: stub %s has no injector %s in Wire's output", stub.Name, stub.DerivedName()))
		}
		constructors = append(constructors, constructor{stub: stub, analysis: ia})
	}

	return constructors
}

// importSet is the emitted file's import block: every package name it uses
// mapped to its path, together with the two names Yama chose for its own
// packages.
type importSet struct {
	paths map[string]string
	yama  string
	rt    string
}

// bodyImports maps each package name the re-emitted bodies refer to onto the
// path Wire's output imports it from.
//
// These names cannot move. The body refers to them, and the constructor
// reproduces that body unchanged, so a rename here would have to rewrite the
// re-emission.
func bodyImports(pkg *LoadedPackage, constructors []constructor) map[string]string {
	declared := pkg.importNames()

	paths := map[string]string{}
	for _, c := range constructors {
		nodes := emittedNodes(c.analysis.Injector)
		for _, name := range qualifiers(nodes...) {
			importPath, ok := declared[name]
			if !ok {
				continue
			}
			paths[name] = importPath
		}
	}

	return paths
}

// claim is the name the emitted file refers to importPath by. It adds the
// import under want, escaped if the file's scope already carries that name.
//
// An import Wire's output already carries for that path keeps its own name
// instead. That name is free of the application's package block, because the
// file carrying it type-checks in that same package, and it is free of the
// other claim, because the scope reads the chosen names as they are recorded.
func (s *importSet) claim(scope *fileScope, want, importPath string) string {
	for name, existing := range s.paths {
		if existing == importPath {
			return name
		}
	}

	name := freeName(want, scope.collides)
	s.paths[name] = importPath

	return name
}

// fileScope is every identifier the emitted file cannot use for an import: the
// identifiers its own constructors write, the import names it has already
// chosen, and the package block it shares with the application, which reaches
// the predeclared identifiers through it.
//
// Go forbids one identifier in both a file block and the package block, so an
// import name has to clear the whole package and not only the file Yama writes.
//
// The scope is read from the package as one build configuration loads it. A
// declaration behind a build tag that load did not carry is not in it.
type fileScope struct {
	pkg   *types.Scope
	bound map[string]bool
	set   *importSet
}

// newFileScope reads the scope of the file Emit is about to write.
//
// The constructors must already be rebound: a cleanup local reaches the scope
// under the name rebindCleanups gave it, not the name Wire gave it. The options
// parameters are deliberately left out, because their names are chosen against
// this scope and recorded as each one is chosen.
func newFileScope(pkg *LoadedPackage, set *importSet, constructors []constructor) *fileScope {
	s := &fileScope{bound: map[string]bool{}, set: set}
	if pkg.Package != nil && pkg.Package.Types != nil {
		s.pkg = pkg.Package.Types.Scope()
	}

	for _, c := range constructors {
		s.bind(c.stub.Name)

		inj := c.analysis.Injector
		for _, f := range inj.Params {
			s.bind(f.Name)
		}
		for _, name := range emittedIdents(inj) {
			s.bind(name)
		}
	}

	return s
}

// bind records one identifier. An empty or blank name binds nothing.
func (s *fileScope) bind(name string) {
	if name == "" || name == "_" {
		return
	}

	s.bound[name] = true
}

// collides reports whether the emitted file already uses name.
func (s *fileScope) collides(name string) bool {
	if s.bound[name] {
		return true
	}
	if _, ok := s.set.paths[name]; ok {
		return true
	}
	if s.pkg == nil {
		return false
	}

	_, obj := s.pkg.LookupParent(name, token.NoPos)

	return obj != nil
}

// bindOptsNames names each constructor's Option parameter, and records the name
// in the scope.
//
// The stub's own name is kept unless the re-emitted body needs it for a package
// the body refers to. No import rename frees the name in that case, because the
// parameter shadows the import inside the very body that refers to it. A
// parameter is positional, so renaming it reaches no caller.
//
// A stub that declares no options parameter is skipped, and its constructor
// keeps an empty name.
func bindOptsNames(scope *fileScope, constructors []constructor) {
	for i := range constructors {
		if !constructors[i].stub.HasOpts {
			continue
		}

		name := freeName(constructors[i].stub.OptsName(), scope.collides)
		scope.bind(name)
		constructors[i].opts = name
	}
}

// emittedNodes are the AST nodes a constructor reproduces, which is what decides
// whether an import Wire's output carries is still needed.
func emittedNodes(inj *Injector) []ast.Node {
	nodes := make([]ast.Node, 0, len(inj.Params)+len(inj.FuncDecl.Body.List)+1)
	for _, f := range inj.Params {
		nodes = append(nodes, f.Type)
	}
	if resultType := inj.ResultType(); resultType != nil {
		nodes = append(nodes, resultType)
	}
	for _, stmt := range constructionStmts(inj) {
		nodes = append(nodes, stmt)
	}
	for _, c := range inj.Components {
		if c.ValueExpr != nil {
			nodes = append(nodes, c.ValueExpr)
		}
	}
	if len(inj.Return.Results) > 0 {
		nodes = append(nodes, inj.Return.Results[0])
	}

	return nodes
}

// emittedIdents names every identifier a constructor's body binds or refers to.
//
// The walk is deliberately loose. It also collects a selector's field name and a
// composite literal's keys, which are not identifiers an import could collide
// with. A scope predicate is safe when it claims too much and unsafe when it
// claims too little, so the extra names stay.
func emittedIdents(inj *Injector) []string {
	var names []string
	for _, node := range emittedNodes(inj) {
		ast.Inspect(node, func(n ast.Node) bool {
			if id, ok := n.(*ast.Ident); ok {
				names = append(names, id.Name)
			}

			return true
		})
	}

	return names
}

// constructionStmts are the injector body's statements without its final return,
// which the constructor replaces with one of its own.
func constructionStmts(inj *Injector) []ast.Stmt {
	body := inj.FuncDecl.Body.List

	return body[:len(body)-1]
}

// importNames maps each package name Wire's output refers to onto its import
// path, preferring the type-checked package's own name over the import path's
// last element.
func (p *LoadedPackage) importNames() map[string]string {
	known := make(map[string]string, len(p.Package.Imports))
	for importPath, imported := range p.Package.Imports {
		if imported.Name != "" {
			known[importPath] = imported.Name
		}
	}

	return fileImports(p.Syntax, known)
}

// rebindCleanups renames each Google Wire cleanup to a name derived from the
// value it releases, and rewrites every reference to it in the injector body.
//
// It edits the parsed injector in place. Running it again over an injector it
// already rebound changes nothing, since each name derives from its value rather
// than from the name it replaces.
func rebindCleanups(inj *Injector) {
	taken := map[string]bool{}
	for _, f := range inj.Params {
		if f.Name != "" {
			taken[f.Name] = true
		}
	}
	for _, c := range inj.Components {
		taken[c.Name] = true
		if c.Cleanup != nil {
			taken[c.Cleanup.Name] = true
		}
	}

	renames := map[string]string{}
	for _, c := range inj.Components {
		if c.Cleanup == nil {
			continue
		}

		delete(taken, c.Cleanup.Name)
		bound := freeName(c.Name+"Cleanup", func(n string) bool { return taken[n] })
		taken[bound] = true
		if bound != c.Cleanup.Name {
			renames[c.Cleanup.Name] = bound
			c.Cleanup.Name = bound
		}
	}

	applyRenames(inj.FuncDecl.Body, renames)
}

// applyRenames rewrites every value identifier under node whose name renames
// covers. It descends into the base of a qualified identifier and the value of a
// composite-literal element only, so a field name that happens to match a
// renamed value is left alone.
func applyRenames(node ast.Node, renames map[string]string) {
	if len(renames) == 0 {
		return
	}

	ast.Inspect(node, func(n ast.Node) bool {
		switch e := n.(type) {
		case *ast.SelectorExpr:
			applyRenames(e.X, renames)
			return false
		case *ast.KeyValueExpr:
			applyRenames(e.Value, renames)
			return false
		case *ast.Ident:
			if bound, ok := renames[e.Name]; ok {
				e.Name = bound
			}
			return false
		}

		return true
	})
}

// freeName is want, or want with the lowest decimal suffix from 2 upward that
// collides reports free.
//
// It records nothing. A caller that makes two choices over one scope must make
// the first visible to collides before it makes the second.
func freeName(want string, collides func(string) bool) string {
	name := want
	for i := 2; collides(name); i++ {
		name = want + strconv.Itoa(i)
	}

	return name
}

// renderFile assembles the whole lifecycle file and gofmts it. Text this
// emitter built that Go cannot parse is a defect in the emitter, and the
// unformatted text is what shows where the defect is, so it comes back beside
// the error rather than being dropped.
func renderFile(sp *StubPackage, pkg *LoadedPackage, imports *importSet, constructors []constructor) ([]byte, error) {
	var buf bytes.Buffer

	fmt.Fprintf(&buf, "%s\n\n", generatedHeader)
	fmt.Fprintf(&buf, "//go:build !%s\n\n", yamaInjectTag)
	fmt.Fprintf(&buf, "package %s\n", sp.PkgName)
	writeEmittedImports(&buf, imports)

	for _, c := range constructors {
		buf.WriteString("\n")
		writeConstructor(&buf, pkg.Fset, imports, c)
	}

	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return buf.Bytes(), fmt.Errorf("yama: emitted invalid Go for %s: %w", sp.Dir, err)
	}

	return formatted, nil
}

// writeEmittedImports writes the import declaration, standard-library packages
// first and the rest after a blank line, each group ordered by path. An import
// carries an explicit name when the path's last element is not that name.
func writeEmittedImports(buf *bytes.Buffer, imports *importSet) {
	var std, other []string
	for name, importPath := range imports.paths {
		if isStdlibPath(importPath) {
			std = append(std, name)
			continue
		}
		other = append(other, name)
	}

	byPath := func(group []string) {
		sort.Slice(group, func(i, j int) bool {
			return imports.paths[group[i]] < imports.paths[group[j]]
		})
	}
	byPath(std)
	byPath(other)

	buf.WriteString("\nimport (\n")
	writeImportGroup(buf, imports, std)
	if len(std) > 0 && len(other) > 0 {
		buf.WriteString("\n")
	}
	writeImportGroup(buf, imports, other)
	buf.WriteString(")\n")
}

// writeImportGroup writes one group of import specs.
func writeImportGroup(buf *bytes.Buffer, imports *importSet, names []string) {
	for _, name := range names {
		importPath := imports.paths[name]
		if path.Base(importPath) == name {
			fmt.Fprintf(buf, "\t%s\n", strconv.Quote(importPath))
			continue
		}
		fmt.Fprintf(buf, "\t%s %s\n", name, strconv.Quote(importPath))
	}
}

// isStdlibPath reports whether an import path names a standard-library package.
// A standard-library path's first element carries no dot, which is the rule the
// Go toolchain's own import grouping uses.
func isStdlibPath(importPath string) bool {
	first, _, _ := strings.Cut(importPath, "/")

	return !strings.Contains(first, ".")
}

// writeConstructor writes one lifecycle constructor: the stub's documentation,
// the signature the stub declared, the re-emitted construction, and the level
// declaration.
func writeConstructor(buf *bytes.Buffer, fset *token.FileSet, imports *importSet, c constructor) {
	inj := c.analysis.Injector

	writeDoc(buf, c.stub.Doc)

	params := printFields(fset, inj.Params)
	if c.opts != "" {
		if params != "" {
			params += ", "
		}
		params += fmt.Sprintf("%s ...%s.%s", c.opts, imports.yama, optionTypeName)
	}

	result := printNode(fset, inj.ResultType())
	fmt.Fprintf(buf, "func %s(%s) (%s, %s.%s, error) {\n",
		c.stub.Name, params, result, imports.yama, lifecycleTypeName)

	writeConstruction(buf, fset, inj)
	writeLevels(buf, fset, imports, c)

	buf.WriteString("}\n")
}

// writeDoc reproduces the stub's documentation comment on the constructor the
// stub declares, so the application's own words reach the file an application
// reads.
func writeDoc(buf *bytes.Buffer, doc *ast.CommentGroup) {
	if doc == nil {
		return
	}

	for _, comment := range doc.List {
		fmt.Fprintf(buf, "%s\n", comment.Text)
	}
}

// writeConstruction reproduces the injector body up to its final return. A
// wire.Value or wire.InterfaceValue provider is written as its own value
// expression, since the variable Wire bound it to lives in the file Yama
// removes.
func writeConstruction(buf *bytes.Buffer, fset *token.FileSet, inj *Injector) {
	stmts := constructionStmts(inj)
	if len(stmts) == 0 {
		return
	}

	values := map[ast.Stmt]*Component{}
	for _, c := range inj.Components {
		if c.Provider == ProviderValue {
			values[c.Assign] = c
		}
	}

	for _, stmt := range stmts {
		if c, ok := values[stmt]; ok {
			fmt.Fprintf(buf, "\t%s := %s\n", c.Name, printNode(fset, c.ValueExpr))
			continue
		}
		fmt.Fprintf(buf, "%s\n", indent(printNode(fset, stmt)))
	}
	buf.WriteString("\n")
}

// writeLevels writes the constructor's return: the value the graph builds, the
// Lifecycle the builder seals, and a nil error. Every level the analysis
// computed is one NextLevel call, and every member of that level is one call
// after it.
func writeLevels(buf *bytes.Buffer, fset *token.FileSet, imports *importSet, c constructor) {
	root := printNode(fset, c.analysis.Injector.Return.Results[0])

	optsArg := ""
	if c.opts != "" {
		optsArg = c.opts + "..."
	}

	fmt.Fprintf(buf, "\treturn %s,\n", root)
	fmt.Fprintf(buf, "\t\t%s.NewLifecycleBuilder(%s).\n", imports.rt, optsArg)
	for _, level := range c.analysis.Levels {
		buf.WriteString("\t\t\tNextLevel().\n")
		for _, m := range level {
			fmt.Fprintf(buf, "\t\t\t%s.\n", memberCall(m))
		}
	}
	buf.WriteString("\t\t\tBuild(),\n")
	buf.WriteString("\t\tnil\n")
}

// memberCall is the builder call that adds one level member, chosen by the kind
// of member it is.
func memberCall(m Member) string {
	switch m.Kind() {
	case MemberComponent:
		return fmt.Sprintf("WithComponents(%s)", m.Component.Name)
	case MemberCleanableComponent:
		return fmt.Sprintf("WithCleanableComponent(%s, %s)", m.Component.Name, m.Component.Cleanup.Name)
	case MemberCleanup:
		return fmt.Sprintf("WithCleanup(%s)", m.Component.Cleanup.Name)
	default:
		panic("generator: memberCall reached an unknown member kind")
	}
}

// indent shifts rendered source one tab to the right, so a statement printed at
// the left margin sits inside a function body.
func indent(src string) string {
	lines := strings.Split(src, "\n")
	for i, line := range lines {
		if line == "" {
			continue
		}
		lines[i] = "\t" + line
	}

	return strings.Join(lines, "\n")
}
