// Copyright (c) 2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generator

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// sentinelWireGen is content Google Wire would never emit, so finding it intact
// after generation proves the caller's file was preserved rather than regenerated.
const sentinelWireGen = `// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package nogen

// SENTINEL - hand-written stand-in for a caller's committed Wire output.
func Sentinel() string { return "untouched" }
`

// wireGenPathsFor returns the Wire output and backup paths in dir under opts.
func wireGenPathsFor(dir string, opts Options) (gen, backup string) {
	name := opts.wireGenName()

	return filepath.Join(dir, name), filepath.Join(dir, backupNameFor(name))
}

func expectNoTransientArtifacts(dir string, opts Options) {
	GinkgoHelper()

	gen, backup := wireGenPathsFor(dir, opts)
	Expect(gen).NotTo(BeAnExistingFile(), "generated output must not be left behind")
	Expect(backup).NotTo(BeAnExistingFile(), "backup must not be left behind")

	// A run scopes the lifecycle file on the same terms as Wire's output, so a
	// directory it left clean holds neither it nor its backup.
	Expect(filepath.Join(dir, lifecycleGenName)).NotTo(BeAnExistingFile(),
		lifecycleGenName+" must not be left behind")
	Expect(filepath.Join(dir, backupNameFor(lifecycleGenName))).NotTo(BeAnExistingFile(),
		backupNameFor(lifecycleGenName)+" must not be left behind")

	// The derived injectors have no scope. A run removes that file, and never
	// creates a backup of it.
	Expect(filepath.Join(dir, derivedFileName)).NotTo(BeAnExistingFile(),
		derivedFileName+" must not be left behind")
	Expect(filepath.Join(dir, backupNameFor(derivedFileName))).NotTo(BeAnExistingFile(),
		backupNameFor(derivedFileName)+" must never be created")
}

func skipWithoutGo() {
	GinkgoHelper()

	if _, err := exec.LookPath("go"); err != nil {
		Skip("go toolchain not found on PATH")
	}
}

var _ = Describe("a run over a package Wire generates for", func() {
	var (
		ctx    context.Context
		dir    string
		opts   Options
		gen    string
		backup string
	)

	BeforeEach(func() {
		skipWithoutGo()
		ctx = context.Background()
		dir = filepath.Join("testdata", "nogen")
		opts = Options{}
	})

	// Derived after every BeforeEach has run, so a context that changes dir or
	// opts still gets the paths those settings imply.
	JustBeforeEach(func() {
		gen, backup = wireGenPathsFor(dir, opts)
	})

	AfterEach(func() {
		// The default names are cleared too, so a prefixed spec cannot leave an
		// unprefixed file behind for the next one.
		defaultGen, defaultBackup := wireGenPathsFor(dir, Options{})
		for _, path := range []string{gen, backup, defaultGen, defaultBackup} {
			os.Remove(path)
		}
	})

	// Both starting points end the same way. The second is the state an
	// interrupted run leaves: it moved the caller's file aside and never put it
	// back.
	DescribeTable("returning a Wire output the package already holds",
		func(startUnderBackupName bool) {
			start := gen
			if startUnderBackupName {
				start = backup
			}
			Expect(os.WriteFile(start, []byte(sentinelWireGen), 0o600)).To(Succeed())

			pkg, err := generateFixture(ctx, NewGenerator(opts), dir, []string{"InitRoot"})
			Expect(err).NotTo(HaveOccurred())
			Expect(pkg.Injectors).To(HaveLen(1), "the graph came from Wire's output, not the sentinel")
			Expect(pkg.Injectors[0].Name).To(Equal("InitRoot"))

			content, err := os.ReadFile(gen)
			Expect(err).NotTo(HaveOccurred())
			Expect(string(content)).To(Equal(sentinelWireGen), "the caller's file must survive unchanged")

			Expect(backup).NotTo(BeAnExistingFile(), "the backup must be consumed by the restore")
		},
		Entry("from its own name", false),
		Entry("from the backup name an interrupted run left it under", true),
	)

	Context("when the package holds no Wire output", func() {
		JustBeforeEach(func() {
			Expect(gen).NotTo(BeAnExistingFile(), "fixture must start without a Wire output")
		})

		It("removes the file it generated and leaves no trace", func() {
			pkg, err := generateFixture(ctx, NewGenerator(opts), dir, []string{"InitRoot"})
			Expect(err).NotTo(HaveOccurred())
			Expect(pkg.Injectors).To(HaveLen(1))

			expectNoTransientArtifacts(dir, opts)
		})
	})

	Context("with an output-file prefix", func() {
		BeforeEach(func() {
			opts = Options{OutputFilePrefix: "foo_"}
		})

		JustBeforeEach(func() {
			Expect(os.WriteFile(gen, []byte(sentinelWireGen), 0o600)).To(Succeed())
		})

		// Yama builds the name by Wire's own rule, so the file it generates,
		// preserves and removes is the one Wire actually wrote.
		It("names the output and its backup after the prefix", func() {
			Expect(opts.wireGenName()).To(Equal("foo_wire_gen.go"), "Wire prepends the prefix verbatim")
			Expect(backup).To(Equal(filepath.Join(dir, ".yama.foo_wire_gen.go")))

			pkg, err := generateFixture(ctx, NewGenerator(opts), dir, []string{"InitRoot"})
			Expect(err).NotTo(HaveOccurred())
			Expect(pkg.Injectors).To(HaveLen(1))
			Expect(pkg.Injectors[0].Name).To(Equal("InitRoot"))

			content, err := os.ReadFile(gen)
			Expect(err).NotTo(HaveOccurred())
			Expect(string(content)).To(Equal(sentinelWireGen), "the caller's prefixed file must survive unchanged")

			Expect(backup).NotTo(BeAnExistingFile(), "the prefixed backup must be consumed by the restore")

			unprefixed, _ := wireGenPathsFor(dir, Options{})
			Expect(unprefixed).NotTo(BeAnExistingFile(), "Wire must not have written an unprefixed file")
		})
	})

	Context("when Wire rejects the package", func() {
		BeforeEach(func() {
			dir = filepath.Join("testdata", "badwire")
		})

		It("still restores the directory", func() {
			_, err := generateFixture(ctx, NewGenerator(opts), dir, []string{"InitRoot"})
			Expect(err).To(HaveOccurred(), "badwire has no provider for *Base")

			expectNoTransientArtifacts(dir, opts)
		})
	})

})

var _ = Describe("wireGenScope", func() {
	var (
		dir    string
		name   string
		gen    string
		backup string
	)

	BeforeEach(func() {
		dir = GinkgoT().TempDir()
		name = Options{}.wireGenName()
		gen, backup = wireGenPathsFor(dir, Options{})
	})

	// Wire writing its own output into the slot the scope prepared.
	generate := func() {
		GinkgoHelper()

		Expect(os.WriteFile(gen, []byte("generated\n"), 0o600)).To(Succeed())
	}

	Context("when neither the file nor a backup exists", func() {
		It("takes no backup, and removes what it generated", func() {
			scope, err := openWireGenScope(dir, name)
			Expect(err).NotTo(HaveOccurred())
			Expect(backup).NotTo(BeAnExistingFile(), "there is no file to hold")

			generate()
			Expect(scope.restore()).To(Succeed())

			Expect(gen).NotTo(BeAnExistingFile())
			Expect(backup).NotTo(BeAnExistingFile())
		})
	})

	Context("when the file exists and no backup does", func() {
		BeforeEach(func() {
			Expect(os.WriteFile(gen, []byte("original\n"), 0o600)).To(Succeed())
		})

		It("backs it up, and puts it back verbatim", func() {
			scope, err := openWireGenScope(dir, name)
			Expect(err).NotTo(HaveOccurred())
			Expect(gen).NotTo(BeAnExistingFile(), "the file is moved aside for the duration")
			Expect(backup).To(BeAnExistingFile())

			generate()
			Expect(scope.restore()).To(Succeed())

			Expect(os.ReadFile(gen)).To(Equal([]byte("original\n")))
			Expect(backup).NotTo(BeAnExistingFile())
		})
	})

	// A backup is taken only to hold a caller's file, so one found here is a
	// caller's file an interrupted run moved aside.
	Context("when a backup exists and the file does not", func() {
		BeforeEach(func() {
			Expect(os.WriteFile(backup, []byte("original\n"), 0o600)).To(Succeed())
		})

		It("keeps the backup, and puts it back", func() {
			scope, err := openWireGenScope(dir, name)
			Expect(err).NotTo(HaveOccurred())

			generate()
			Expect(scope.restore()).To(Succeed())

			Expect(os.ReadFile(gen)).To(Equal([]byte("original\n")))
			Expect(backup).NotTo(BeAnExistingFile())
		})
	})

	// The interrupted run left its own output behind under the name it had
	// already vacated, so the file here is Wire's, not a caller's.
	Context("when both the file and a backup exist", func() {
		BeforeEach(func() {
			Expect(os.WriteFile(gen, []byte("junk\n"), 0o600)).To(Succeed())
			Expect(os.WriteFile(backup, []byte("original\n"), 0o600)).To(Succeed())
		})

		It("keeps the backup, discards the file, and puts the backup back", func() {
			scope, err := openWireGenScope(dir, name)
			Expect(err).NotTo(HaveOccurred())
			Expect(gen).NotTo(BeAnExistingFile(), "the interrupted run's output is gone")
			Expect(os.ReadFile(backup)).To(Equal([]byte("original\n")))

			generate()
			Expect(scope.restore()).To(Succeed())

			Expect(os.ReadFile(gen)).To(Equal([]byte("original\n")))
			Expect(backup).NotTo(BeAnExistingFile())
		})
	})
})

var _ = Describe("openWireGenScopes", func() {
	// A partial open would leave the directories already scoped holding their
	// callers' files under backup names, with no caller left to put them back.
	It("rolls back the scopes it opened when a later one fails", func() {
		root := GinkgoT().TempDir()
		opts := Options{}

		first := filepath.Join(root, "first")
		Expect(os.Mkdir(first, 0o750)).To(Succeed())
		firstGen, firstBackup := wireGenPathsFor(first, opts)
		Expect(os.WriteFile(firstGen, []byte("original\n"), 0o600)).To(Succeed())

		// A backup makes the scope remove the file beside it, and a directory
		// holding an entry cannot be removed.
		second := filepath.Join(root, "second")
		Expect(os.Mkdir(second, 0o750)).To(Succeed())
		secondGen, secondBackup := wireGenPathsFor(second, opts)
		Expect(os.Mkdir(secondGen, 0o750)).To(Succeed())
		Expect(os.WriteFile(filepath.Join(secondGen, "keep.txt"), []byte("x"), 0o600)).To(Succeed())
		Expect(os.WriteFile(secondBackup, []byte("second original\n"), 0o600)).To(Succeed())

		scopes, err := openWireGenScopes([]string{first, second}, opts.wireGenName())
		Expect(err).To(HaveOccurred())
		Expect(scopes).To(BeNil())

		Expect(os.ReadFile(firstGen)).To(Equal([]byte("original\n")),
			"the directory opened before the failure is rolled back")
		Expect(firstBackup).NotTo(BeAnExistingFile())
	})
})

// The leading dot is load-bearing: without it the Go toolchain would compile the
// backup as a source file, colliding with the regenerated one it sits beside. The
// name is built from whatever Wire wrote, so a prefixed output is backed up under a
// matching prefixed name rather than the unprefixed default.
var _ = DescribeTable("the backup name tracks the Wire output",
	func(prefix string) {
		name := Options{OutputFilePrefix: prefix}.wireGenName()
		backup := backupNameFor(name)

		Expect(name).To(Equal(prefix+"wire_gen.go"), "Wire prepends the prefix verbatim")
		Expect(backup).To(HavePrefix("."), "the Go toolchain must skip the backup as a source file")
		Expect(backup).To(HaveSuffix(name), "the backup is built from the Wire output name")
		Expect(backup).NotTo(Equal(name))
	},
	Entry("no prefix", ""),
	Entry("prefix ending in a separator", "foo_"),
	Entry("prefix without a separator", "bar"),
)
