// Copyright (c) 2026 the original author or authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package generator

import (
	"context"
	"os"
	"os/exec"
	"path/filepath"

	. "github.com/onsi/ginkgo/v2"
	. "github.com/onsi/gomega"
)

// sentinelWireGen is content Google Wire would never emit, so finding it intact
// after generation proves the caller's file was preserved rather than regenerated.
const sentinelWireGen = `// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject

package nogen

// SENTINEL - hand-written stand-in for a caller's committed Wire output.
func Sentinel() string { return "untouched" }
`

// wireGenPathsFor returns the Wire output and backup paths in dir under opts.
func wireGenPathsFor(dir string, opts Options) (gen, backup string) {
	name := opts.wireGenName()

	return filepath.Join(dir, name), filepath.Join(dir, backupNameFor(name))
}

func expectNoWireGenArtifacts(dir string, opts Options) {
	GinkgoHelper()

	gen, backup := wireGenPathsFor(dir, opts)
	Expect(gen).NotTo(BeAnExistingFile(), "generated output must not be left behind")
	Expect(backup).NotTo(BeAnExistingFile(), "backup must not be left behind")
}

func skipWithoutGo() {
	GinkgoHelper()

	if _, err := exec.LookPath("go"); err != nil {
		Skip("go toolchain not found on PATH")
	}
}

var _ = Describe("Generate", func() {
	var (
		ctx    context.Context
		dir    string
		opts   Options
		gen    string
		backup string
	)

	BeforeEach(func() {
		skipWithoutGo()
		ctx = context.Background()
		dir = filepath.Join("testdata", "nogen")
		opts = Options{}
	})

	// Derived after every BeforeEach has run, so a context that changes dir or
	// opts still gets the paths those settings imply.
	JustBeforeEach(func() {
		gen, backup = wireGenPathsFor(dir, opts)
	})

	AfterEach(func() {
		// The default names are cleared too, so a prefixed spec cannot leave an
		// unprefixed file behind for the next one.
		defaultGen, defaultBackup := wireGenPathsFor(dir, Options{})
		for _, path := range []string{gen, backup, defaultGen, defaultBackup} {
			os.Remove(path)
		}
	})

	Context("when the package already holds a Wire output", func() {
		JustBeforeEach(func() {
			Expect(os.WriteFile(gen, []byte(sentinelWireGen), 0o600)).To(Succeed())
		})

		It("returns that file untouched and consumes the backup", func() {
			pkg, err := NewGenerator(opts).Generate(ctx, dir)
			Expect(err).NotTo(HaveOccurred())
			Expect(pkg.Injectors).To(HaveLen(1), "the graph came from Wire's output, not the sentinel")
			Expect(pkg.Injectors[0].Name).To(Equal("InitRoot"))

			content, err := os.ReadFile(gen)
			Expect(err).NotTo(HaveOccurred())
			Expect(string(content)).To(Equal(sentinelWireGen), "the caller's file must survive unchanged")

			Expect(backup).NotTo(BeAnExistingFile(), "the backup must be consumed by the restore")
		})
	})

	Context("when the package holds no Wire output", func() {
		JustBeforeEach(func() {
			Expect(gen).NotTo(BeAnExistingFile(), "fixture must start without a Wire output")
		})

		It("removes the file it generated and leaves no trace", func() {
			pkg, err := NewGenerator(opts).Generate(ctx, dir)
			Expect(err).NotTo(HaveOccurred())
			Expect(pkg.Injectors).To(HaveLen(1))

			expectNoWireGenArtifacts(dir, opts)
		})
	})

	Context("with an output-file prefix", func() {
		BeforeEach(func() {
			opts = Options{OutputFilePrefix: "foo_"}
		})

		JustBeforeEach(func() {
			Expect(os.WriteFile(gen, []byte(sentinelWireGen), 0o600)).To(Succeed())
		})

		// Yama builds the name by Wire's own rule, so the file it generates,
		// preserves and removes is the one Wire actually wrote.
		It("names the output and its backup after the prefix", func() {
			Expect(opts.wireGenName()).To(Equal("foo_wire_gen.go"), "Wire prepends the prefix verbatim")
			Expect(backup).To(Equal(filepath.Join(dir, ".yama.foo_wire_gen.go")))

			pkg, err := NewGenerator(opts).Generate(ctx, dir)
			Expect(err).NotTo(HaveOccurred())
			Expect(pkg.Injectors).To(HaveLen(1))
			Expect(pkg.Injectors[0].Name).To(Equal("InitRoot"))

			content, err := os.ReadFile(gen)
			Expect(err).NotTo(HaveOccurred())
			Expect(string(content)).To(Equal(sentinelWireGen), "the caller's prefixed file must survive unchanged")

			Expect(backup).NotTo(BeAnExistingFile(), "the prefixed backup must be consumed by the restore")

			unprefixed, _ := wireGenPathsFor(dir, Options{})
			Expect(unprefixed).NotTo(BeAnExistingFile(), "Wire must not have written an unprefixed file")
		})
	})

	Context("when Wire rejects the package", func() {
		BeforeEach(func() {
			dir = filepath.Join("testdata", "badwire")
		})

		It("still restores the directory", func() {
			_, err := NewGenerator(opts).Generate(ctx, dir)
			Expect(err).To(HaveOccurred(), "badwire has no provider for *Base")

			expectNoWireGenArtifacts(dir, opts)
		})
	})

	// A real package, not a bare temp directory: Generate resolves the package
	// before opening any scope, exactly as Google Wire loads before generating,
	// so a directory outside a module fails at resolution and never reaches the
	// guard under test.
	Context("when a backup from an interrupted run is present", func() {
		JustBeforeEach(func() {
			Expect(os.WriteFile(backup, []byte("original\n"), 0o600)).To(Succeed())
		})

		// That backup holds the caller's original, so proceeding would overwrite
		// the only copy.
		It("refuses loudly and touches nothing", func() {
			_, err := NewGenerator(opts).Generate(ctx, dir)
			Expect(err).To(HaveOccurred())
			Expect(err.Error()).To(ContainSubstring(backupNameFor(opts.wireGenName())))
			Expect(err.Error()).To(ContainSubstring("interrupted run"))

			content, err := os.ReadFile(backup)
			Expect(err).NotTo(HaveOccurred(), "the stale backup must be left untouched")
			Expect(string(content)).To(Equal("original\n"))
		})
	})
})

var _ = Describe("wireGenScope", func() {
	var (
		dir    string
		name   string
		gen    string
		backup string
	)

	BeforeEach(func() {
		dir = GinkgoT().TempDir()
		name = Options{}.wireGenName()
		gen, backup = wireGenPathsFor(dir, Options{})
	})

	Context("when a file of that name already exists", func() {
		BeforeEach(func() {
			Expect(os.WriteFile(gen, []byte("original\n"), 0o600)).To(Succeed())
		})

		It("moves it aside and puts it back verbatim", func() {
			scope, err := openWireGenScope(dir, name)
			Expect(err).NotTo(HaveOccurred())
			Expect(scope.preserved).To(BeTrue())
			Expect(gen).NotTo(BeAnExistingFile(), "the original is moved aside for the duration")
			Expect(backup).To(BeAnExistingFile())

			// Stand in for Wire writing its own output into the vacated slot.
			Expect(os.WriteFile(gen, []byte("generated\n"), 0o600)).To(Succeed())
			Expect(scope.restore()).To(Succeed())

			content, err := os.ReadFile(gen)
			Expect(err).NotTo(HaveOccurred())
			Expect(string(content)).To(Equal("original\n"))
			Expect(backup).NotTo(BeAnExistingFile())
		})

		// Claiming the backup name is the serialization point: without it, two runs
		// would each rename a file onto the same backup and os.Rename would silently
		// replace the first one's preserved original.
		It("turns away a second scope over the same directory", func() {
			first, err := openWireGenScope(dir, name)
			Expect(err).NotTo(HaveOccurred())
			Expect(first.preserved).To(BeTrue())

			second, err := openWireGenScope(dir, name)
			Expect(err).To(HaveOccurred())
			Expect(second).To(BeNil())
			Expect(err.Error()).To(ContainSubstring(backupNameFor(name)))

			Expect(first.restore()).To(Succeed())

			content, err := os.ReadFile(gen)
			Expect(err).NotTo(HaveOccurred())
			Expect(string(content)).To(Equal("original\n"), "the first scope's original survives the second attempt")
		})
	})

	Context("when no file of that name exists", func() {
		// The placeholder must not masquerade as a stranded backup and block the
		// next run.
		It("releases the claim it took", func() {
			scope, err := openWireGenScope(dir, name)
			Expect(err).NotTo(HaveOccurred())
			Expect(scope.preserved).To(BeFalse())
			Expect(backup).To(BeAnExistingFile(), "the claim is held for the life of the scope")

			Expect(os.WriteFile(gen, []byte("generated\n"), 0o600)).To(Succeed())
			Expect(scope.restore()).To(Succeed())

			Expect(gen).NotTo(BeAnExistingFile())
			Expect(backup).NotTo(BeAnExistingFile())

			next, err := openWireGenScope(dir, name)
			Expect(err).NotTo(HaveOccurred(), "the directory is usable again")
			Expect(next.restore()).To(Succeed())
		})
	})
})

// The leading dot is load-bearing: without it the Go toolchain would compile the
// backup as a source file, colliding with the regenerated one it sits beside. The
// name is built from whatever Wire wrote, so a prefixed output is backed up under a
// matching prefixed name rather than the unprefixed default.
var _ = DescribeTable("the backup name tracks the Wire output",
	func(prefix string) {
		name := Options{OutputFilePrefix: prefix}.wireGenName()
		backup := backupNameFor(name)

		Expect(name).To(Equal(prefix+"wire_gen.go"), "Wire prepends the prefix verbatim")
		Expect(backup).To(HavePrefix("."), "the Go toolchain must skip the backup as a source file")
		Expect(backup).To(HaveSuffix(name), "the backup is built from the Wire output name")
		Expect(backup).NotTo(Equal(name))
	},
	Entry("no prefix", ""),
	Entry("prefix ending in a separator", "foo_"),
	Entry("prefix without a separator", "bar"),
)
