// Code generated by Yama. DO NOT EDIT.

//go:generate go tool yama
//go:build !yamainject

package collision

import (
	yama2 "l7e.io/yama"
	rt2 "l7e.io/yama/rt"
)

// NewLifecycle orchestrates a graph whose component locals take the names Yama
// wants for its own imports.
func NewLifecycle(opts ...yama2.Option) (*App, yama2.Lifecycle, error) {
	rt := NewRt()
	yama := NewYama(rt)
	app := NewApp(yama)

	return app,
		rt2.NewLifecycleBuilder(opts...).
			NextLevel().
			WithComponents(rt).
			NextLevel().
			WithComponents(yama).
			NextLevel().
			WithComponents(app).
			Build(),
		nil
}
