// Code generated by Wire. DO NOT EDIT.

//go:build !wireinject
// +build !wireinject

package binaryrhs

// InitializeApp is a single-injector graph. Every statement is a recognized
// provider form EXCEPT retries, whose right-hand side is a binary expression no
// provider kind emits.
func InitializeApp() (*App, error) {
	config := _wireConfigValue
	logger := NewConsoleLogger(config)
	base1 := NewBase1(logger)
	retries := base1.max - 1
	root1 := NewRoot1(logger, base1, retries)
	app := &App{
		root1: root1,
	}
	return app, nil
}

var _wireConfigValue = Config{Env: Prod}
