// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package structcomp

// Injectors from wire.go:

// InitRoot builds Root through a wire.Struct intermediate (Cfg) and a
// cleanup-returning provider (NewB).
func InitRoot() (*Root, func()) {
	a := NewA()
	b, cleanup := NewB()
	cfg := &Cfg{
		A: a,
		B: b,
	}
	server := NewServer(cfg)
	root := NewRoot(server)
	return root, func() {
		cleanup()
	}
}
