// Code generated by Yama. DO NOT EDIT.

//go:build !yamainject

package cleanup

import (
	yama "l7e.io/yama/v2"
	"l7e.io/yama/v2/rt"
)

// NewLifecycle orchestrates a graph whose providers return cleanup functions.
func NewLifecycle(opts ...yama.Option) (*Root, yama.Lifecycle, error) {
	plain, plainCleanup := NewPlain()
	capable, capableCleanup := NewCapable(plain)
	failing, failingCleanup, err := NewFailing(capable)
	if err != nil {
		capableCleanup()
		plainCleanup()
		return nil, nil, err
	}
	root := NewRoot(failing)

	return root,
		rt.NewLifecycleBuilder(opts...).
			NextLevel().
			WithCleanup(plainCleanup).
			NextLevel().
			WithCleanableComponent(capable, capableCleanup).
			NextLevel().
			WithCleanableComponent(failing, failingCleanup).
			NextLevel().
			WithComponents(root).
			Build(),
		nil
}
